### ISSUE TITLE
Change project name to Jakarta EE Platform

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#10]
Background information:
https://waynebeaton.wordpress.com/2019/04/04/renaming-java-ee-specifications-for-jakarta-ee/

Checklist:
- [ ]  GitHub
- [ ]  README file
- [ ]  CONTRIBUTING file
- [ ]  Eclipse Project under https://projects.eclipse.org/projects/ee4j

**Comment by ivargrimstad** [comment]
**Jakarta EE Platform** or simply **Jakarta EE**?

**Comment by keilw** [comment]
I would suggest for the project name Jakarta EE Platform, as there are many other projects under the Jakarta EE umbrella.

**Comment by bshannon** [comment]
I agree, "Jakarta EE Platform".

**Comment by chkal** [comment]
+1 for "Jakarta EE Platform"

**Comment by jeyvison** [comment]
+1  "Jakarta EE Platform"

**Comment by lilian-benoit** [comment]
+1 for "Jakarta EE Platform"
