### ISSUE TITLE
Compatibility certification request for Eclipse Glassfish 5.1 for Managed Beans

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#104]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Eclipse Glassfish 5.1](https://eclipse-ee4j.github.io/glassfish/download)
- [x] Specification Name, Version and download URL:<br/>
   [Managed Beans 1.0](https://jakarta.ee/specifications/managedbeans/1.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE 8 TCK](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip), SHA-256:
  `847c80c9c80bea4682006f186292b68acdd0ce9b239d998856c3a379c3a7be50`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results Summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/8.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements:<br/>
  None
- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Centos 7, Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1

**Comment by bshannon** [comment]
+1

**Comment by bshannon** [comment]
Lacking any objections, I'm marking this approved by lazy consensus.

**Comment by carlosdlr** [comment]
+1
