### ISSUE TITLE
Is JakartaTM correct in WebProfiles?

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jakartaee-platform#105]
**Describe the bug**
The [WebProfileDefinition.adoc](https://github.com/eclipse-ee4j/jakartaee-platform/blob/master/specification/src/main/asciidoc/webprofile/WebProfileDefinition.adoc) says "Jakarta™ EE". Not sure, if that's correct or a left-over from the "Java" term in its place?

**Comment by kwsutter** [comment]
It's good.  Jakarta is the actual (TM).  We don't have to flag every use of it -- normally just the first use within a document.  But, since we had so many people helping with the platform specs, we probably have at least one usage per section.  Oh well, doesn't hurt anything.  Thanks.

**Comment by keilw** [comment]
Ok if it's legitimate and does not violate anything then it's fine.
