### ISSUE TITLE
Portlet JSR outdated in Profiles document

### ISSUE THREAD

**Issue by keilw** [eclipse-ee4j/jakartaee-platform#106]
**Describe the bug**
In the [Profiles](https://github.com/eclipse-ee4j/jakartaee-platform/blob/master/specification/src/main/asciidoc/platform/Profiles.adoc) Asciidoc the version of the Portlet JSR for a hypothetical Portlet Profile should be JSR-362 (Portlet 3.0) not JSR-286.

**Comment by kwsutter** [comment]
Resolved via PR #107
