### ISSUE TITLE
Compatibility certification request for Open Liberty for Full Platform

### ISSUE THREAD

**Issue by shighbar** [eclipse-ee4j/jakartaee-platform#114]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  I[BM Corporation](https://www.ibm.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 19.0.0.6](https://openliberty.io/downloads/)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Full Profile, 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.1](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/staged-801/eclipse-jakartaeetck-8.0.1.zip)
  `026f2b2fc7a2f1e802aed6cf1671d486dc90d1b03fd3519367577aa9f6545fa`
- [x] Public URL of TCK Results Summary:<br/>
  [Test Results](https://openliberty.io/certifications/jakartaee/platform/8/TCKResults.html)
- [x] Any Additional Specification Certification Requirements:<br/>
   Jakarta Injection Specification
    [jakarta.inject-tck-1.0-bin.zip](http://download.eclipse.org/ee4j/cdi/jakarta.inject-tck-1.0-bin.zip),
    `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
    (Weld 3.1.1)

   Jakarta Contexts and Dependency Injection
   [cdi-tck-2.0.6-dist.zip](http://download.eclipse.org/ee4j/cdi/cdi-tck-2.0.6-dist.zip),
   `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`

   Jakarta Bean Validation
   [beanvalidation-tck-dist-2.0.5.tar.gz](http://download.eclipse.org/ee4j/bean-validation/beanvalidation-tck-dist-2.0.5.tar.gz),
   `05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8`

- [x] Java runtime used to run the implementation:<br/>
   OpenJDK 1.8.0_222  (HotSpot)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
   Linux Ubuntu 18.04 LTS, Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

- [x] Relevant challenges & resolution:
     Signaturetest.
     https://github.com/eclipse-ee4j/faces-api/issues/1474

**Comment by edbratt** [comment]
The TCK link points to version 8.0.1. I would recommend the link text include that. Perhaps just copy what you have written out in the TCK summary. Otherwise, looks good to me.

**Comment by bshannon** [comment]
Given the decision of the specification committee to allow the JSF signature test failures,
I was expecting to see those signature test failures in the TCK results, but I don't see them.
Hopefully you didn't modify the TCK to suppress those failures.  Please confirm that the TCK
passed unmodified and that you're no longer taking advantage of the signature test exception.

**Comment by shighbar** [comment]
Bill.  The test results do show 2 signaturetest failures (3 out of the 5 passed) which are the failures caused by the JSF challenged issue. The TCK is unmodified.

**Comment by kwsutter** [comment]
+1 to start the voting

**Comment by sdaschner** [comment]
+1

**Comment by carlosdlr** [comment]
+1

**Comment by ivargrimstad** [comment]
+1

**Comment by bshannon** [comment]
> Bill. The test results do show 2 signaturetest failures (3 out of the 5 passed) which are the failures caused by the JSF challenged issue. The TCK is unmodified.

Ah, ok, I found it.  But I think we need to see the details of the failures so that we know the
failures are exactly and only the ones approved by the spec committee.

**Comment by bshannon** [comment]
+1

I'd like the TCK results to include the details of the failures, but generally this is fine.

**Comment by dblevins** [comment]
+1

**Comment by dblevins** [comment]
Going to mark this accepted so everyone can sleep well.

**Comment by smillidge** [comment]
+1

**Comment by smillidge** [comment]
@kwsutter I noticed the download URL for your TCK is referencing a staged artefact. Do you want to change it to the final?

**Comment by kwsutter** [comment]
> @kwsutter I noticed the download URL for your TCK is referencing a staged artefact. Do you want to change it to the final?

Thanks, @smillidge.  This was a case of us testing and submitting the results before the final 8.0.1 TCK was posted...  I've updated it here and will update the TCK Results page.  Thanks again.
