### ISSUE TITLE
Compatibility certification request for WildFly for Full Profile

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#116]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Red Hat, https://www.redhat.com
- [x] Product Name, Version and download URL (if applicable):<br/>
  WildFly, 17.0.1.Final, https://wildfly.org/downloads
- [x] Specification Name, Version and download URL:<br/>
   Jakarta EE Platform, 8, https://jakarta.ee/specifications/platform/8/
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
Jakarta EE Platform CTS 8.0 SHA-256 847c80c9c80bea4682006f186292b68acdd0ce9b239d998856c3a379c3a7be50   https://download.eclipse.org/jakartaee/full-profile/8/eclipse-jakartaeetck-8.0.0.zip
- [x] Public URL of TCK Results Summary:<br/>
  https://github.com/wildfly/certifications/blob/EE8/WildFly_17.0.1.Final/jakarta-full-profile.adoc
- [x] Any Additional Specification Certification Requirements:<br/>

Jakarta Dependency Injection 1.0 TCK:
[jakarta.inject-tck-1.0-bin.zip](http://download.eclipse.org/ee4j/cdi/jakarta.inject-tck-1.0-bin.zip)
b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f

Jakarta Contexts and Dependency Injection 2.0 TCK:
[cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/ee4j/cdi/cdi-tck-2.0.6-dist.zip)
SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808

Jakarta Bean Validation 2.0 TCK:
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974
- [x] Java runtime used to run the implementation:<br/>
Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS version: Red Hat Enterprise Linux Server 7.4 (Maipo)
Database version:   Apache Derby Network Server 10.14.2.0
Database JDBC Driver and version:  Apache Derby 10.14.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
@scottmarlow The URL for the Platform 8.0 TCK is not accurate.  I'm pretty sure you meant "platform" and not "full-profile".

Are the TCK Results as an adoc file in the github repo "persistent" enough?  I guess I was expecting some URL of a website or wiki.  Pointing at the github repo is probably fine in a pinch, but it surprised me.

Formatting issues on the references to the CDI, DI, and Bean Validation TCKs.

**Comment by scottmarlow** [comment]
@kwsutter 

> The URL for the Platform 8.0 TCK is not accurate. I'm pretty sure you meant "platform" and not "full-profile".

I updated the link and name, thanks!

> Are the TCK Results as an adoc file in the github repo "persistent" enough? I guess I was expecting some URL of a website or wiki. Pointing at the github repo is probably fine in a pinch, but it surprised me.

I like that github shows modifications to the TCK Results, in an easy to view way.  Websites are excellent choices for displaying the results also.

**Comment by bshannon** [comment]
+1

**Comment by dblevins** [comment]
+1

**Comment by dblevins** [comment]
+1

Going to mark this accepted so everyone can sleep well.  Leaving it open to encourage more votes.

**Comment by kwsutter** [comment]
+1  Looks good, @scottmarlow!  thanks for the updates

**Comment by scottmarlow** [comment]
Thanks all!  I noticed an issue in the results URL (master branch is used), I'm changing from https://github.com/wildfly/certifications/blob/master/WildFly_17.0.1.Final/jakarta-full-profile.adoc to https://github.com/wildfly/certifications/blob/EE8/WildFly_17.0.1.Final/jakarta-full-profile.adoc.

**Comment by shabnammayel** [comment]
just to confirm WildFly will be included in the Jakarta EE 8 Full Platform Compatible Products section https://deploy-preview-453--jakartaee.netlify.com/compatibility/

**Comment by smillidge** [comment]
+1
