### ISSUE TITLE
Compatibility certification request for Payara Server for Full Platform

### ISSUE THREAD

**Issue by pdudits** [eclipse-ee4j/jakartaee-platform#119]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Payara Services Ltd](https://www.payara.fish/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Payara Server 5.193.1](https://www.payara.fish/software/downloads/)
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform CTS 8.0.1](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.1.zip), SHA-256: `3026f2b2fc7a2f1e802aed6cf1671d486dc90d1b03fd3519367577aa9f6545fa`
- [x] Public URL of TCK Results Summary:<br/>
https://docs.payara.fish/v/master/jakartaee-certification/5.193/tck-results-full-5.193.1.html
- [x] Any Additional Specification Certification Requirements:
  - Jakarta Dependency Injection 1.0 TCK
    Download URL & SHA-256: 
    [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  - Jakarta Contexts and Dependency Injection 2.0 TCK
    Download URL & SHA-256: 
[cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip),   `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  - Jakarta Bean Validation 2.0 TCK, 
    See test results in section `beanvalidation`.
    Download URL & SHA-256: 
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`

- [X] Java runtime used to run the implementation:<br/>
  OpenJDK 1.8.0_222 (Zulu)
- [X] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Ubuntu 18.04 LTS
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
This looks good to me.  Thanks, Payara!  We'll leave this open for a bit to see if there are any other comments, but otherwise it looks good.

**Comment by carlosdlr** [comment]
+1 LGTM Thanks payara team

**Comment by ivargrimstad** [comment]
I'm getting a dfferent sha256 for the beanvalidation TCK, but it may be me doing it wrong. Anyone else getting 'b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974'?

**Comment by pdudits** [comment]
You are right, @ivargrimstad I double checked the cached artifact we've run against, will update the request.

**Comment by smillidge** [comment]
SHA is now correct for BV.

**Comment by bshannon** [comment]
+1

**Comment by ivargrimstad** [comment]
+1

**Comment by keilw** [comment]
Who's supposed to review or confirm that, everyone in the Spec Committee?

**Comment by kwsutter** [comment]
Platform project lead just has to accept.  I will do that now!

**Comment by scottmarlow** [comment]
@pdudits is there a new link that replaces [https://docs.payara.fish/v/master/jakartaee-certification/5.193/tck-results-full-5.193.1.html](https://docs.payara.fish/v/master/jakartaee-certification/5.193/tck-results-full-5.193.1.html)?

**Comment by pdudits** [comment]
@scottmarlow it looks something happened to our branch urls: https://docs.payara.fish/jakartaee-certification/5.193/tck-results-full-5.193.1.html

**Comment by scottmarlow** [comment]
Thanks @pdudits, that helps me validate what I am seeing with the 8.0.2 TCK
