### ISSUE TITLE
Compatibility certification request for WildFly for Full Platform

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#121]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Red Hat](https://www.redhat.com)

- [x] Product Name, Version and download URL (if applicable):<br/>
  [WildFly 18.0.0.Final](https://wildfly.org/downloads)

- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, Full Platform, 8](https://jakarta.ee/specifications/platform/8/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.1](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.1.zip)

`SHA-256: 3026f2b2fc7a2f1e802aed6cf1671d486dc90d1b03fd3519367577aa9f6545fa`

- [x] Public URL of TCK Results Summary:<br/>
  [Test Results](https://github.com/wildfly/certifications/blob/EE8/WildFly_18.0.0.Final/jakarta-full-platform.adoc)

- [x] Any Additional Specification Certification Requirements:<br/>

[Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/ee4j/cdi/jakarta.inject-tck-1.0-bin.zip)
`SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`

[Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/ee4j/cdi/cdi-tck-2.0.6-dist.zip)
`SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`

[Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
`SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`

- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS version: Red Hat Enterprise Linux Server 7.4 (Maipo)
Database version: Apache Derby Network Server 10.14.2.0
Database JDBC Driver and version: Apache Derby 10.14.2.0

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
The SHA 256 signature for the 8.0.1 TCK isn't right... Did you possibly run with a different version?

**Comment by scottmarlow** [comment]
Oops, I'll correct that, we did:

> wget -q --no-check-certificate https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.1.zip
> sha256sum jakartaeetck.zip
> 3026f2b2fc7a2f1e802aed6cf1671d486dc90d1b03fd3519367577aa9f6545fa  jakartaeetck.zip

We switched a few days ago from the staged tck to the correct link, I missed updating the SHA 256 signature.  

Thanks also Sharon for texting me about the ^ :)

**Comment by smillidge** [comment]
+1

**Comment by carlosdlr** [comment]
+1

**Comment by kwsutter** [comment]
+1, Looks good, @scottmarlow!

**Comment by ivargrimstad** [comment]
+1

**Comment by kazumura** [comment]
+1

**Comment by bshannon** [comment]
+1
