### ISSUE TITLE
Create a javax-to-jakarta conversion guide

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#125]
Describe the steps needed in order to transform a specification from the `javax.*` namespace to `jakarta.*`. This document will be used as input to the specification projects as well as for estimations needed in order to produce the Jakarta EE 9 Delivery Plan.

**Comment by kwsutter** [comment]
@ivargrimstad, do you think this is still a required doc?  It looks like most teams are already well on their way with the conversion.  And, in my mind, this is a pretty straight forward operation.  Am I missing something with this proposal?  Thanks.

**Comment by hantsy** [comment]
I hope there is a tool(a script or maven plugin) to automate the working, and also provide suggestions on how old applications to migrate to jakarta.ee.

For example, run in a Java EE 8 application, suggest **replace `javaee-api`->`jakarta.jakartaee-api`** etc.

**Comment by hantsy** [comment]
Found a great tools for this purpose, https://github.com/apache/tomcat-jakartaee-migration
