### ISSUE TITLE
Compatibility certification request for Payara Server 5.194 for Full Platform

### ISSUE THREAD

**Issue by pdudits** [eclipse-ee4j/jakartaee-platform#131]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Payara Services Ltd](https://www.payara.fish/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Payara Server 5.194](https://www.payara.fish/software/downloads/)
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform CTS 8.0.1](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.1.zip), SHA-256: `3026f2b2fc7a2f1e802aed6cf1671d486dc90d1b03fd3519367577aa9f6545fa`
- [x] Public URL of TCK Results Summary:<br/>
https://docs.payara.fish/jakartaee-certification/5.194/tck-results-full-5.194.html
- [x] Any Additional Specification Certification Requirements:
  - Jakarta Dependency Injection 1.0 TCK
    Download URL & SHA-256: 
    [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  - Jakarta Contexts and Dependency Injection 2.0 TCK
    Download URL & SHA-256: 
[cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip),   `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  - Jakarta Bean Validation 2.0 TCK, 
    See test results in section `beanvalidation`.
    Download URL & SHA-256: 
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`

- [X] Java runtime used to run the implementation:<br/>
  OpenJDK 1.8.0_222 (Zulu)
- [X] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Ubuntu 18.04 LTS
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
I'm just cleaning up old issues and found this one.  A couple of questions...

- Payara is already listed on the compatibility page with version 5.193.1.  Are you looking to replace that compatibility with version 5.194?

- On that same vein, have you already submitted the request to update the jakarta.ee compatibility page?

- The [link for the TCK results](https://docs.payara.fish/v/master/jakartaee-certification/5.194/tck-results-full-5.194.html) doesn't work for me.

Thanks!

**Comment by pdudits** [comment]
Hi,

I updated the link, the prerelease-one stopped working.

I was looking to add a next compatible version, since our every release is tested against TCK, if that is not expected to do for each one, I'll yet check what is best approach for us.

**Comment by bshannon** [comment]
I assume that Eclipse wants every compatible (final, released) version to be listed on the page.  Otherwise, if you have version 5.194 and version 5.193.1 is listed on the page, how would you know that the version you have is compatible?

If Eclipse wants to apply looser rules, they should describe what the new rules are.
@waynebeaton, any comments?

**Comment by waynebeaton** [comment]
I assume that you mean the [Jakarta EE Compatible Products](https://jakarta.ee/compatibility/) page.

A request for certification as a compatible implementation is separate from being listed on the  compatible products page. Versions 5.194 and 5.193.1 can both be compatible versions. Agreeing that the compatible implementation satisfies the requirements should be the project team's only consideration here.

Engaging this certification process is a step in the [Get Listed](https://jakarta.ee/compatibility/get_listed/) process.

Regarding the compatible products page, I believe that the current rule is that only one version (presumably the latest) is displayed there. The Eclipse Foundation owns and manages that page, but does so under direction from the Jakarta EE Working Group's Marketing Committee. If change to the rules is desired, I recommend that you take it up with them.

Let me know if I've misunderstood the question.

**Comment by bshannon** [comment]
@waynebeaton actually, I was thinking of the list of compatible implementations on
the page for a given specification version.

Surely there must be some page that lists all the current and historical compatible
versions of a product?  Do you expect that to be *only* the specification page for
the platform specification and not the Compatible Products page?

As each new compatible version of a platform product is released by a vendor, do you
expect them to go through the Get Listed process, resulting in their entry on the
Compatible Products page being updated with the new version?  And then separately
they submit a PR for the platform specification page to add the new version to the
list of Compatible Implementations?

(Note that I'm not asking for a change to the process, just trying to clarify what the
current process requirements are with regard to multiple compatible versions of a
product.)

**Comment by waynebeaton** [comment]
@bshannon, there are no versions of Papyrus Server is currently listed in the compatible implementations section of the [specification version page](https://github.com/jakartaee/specifications/blob/master/platform/8/_index.md). 

The Eclipse Foundation only cares that the Eclipse Foundation Specification Process is followed. How releases are documented is the specification committee's call.

IMHO, it makes sense to list all compatible products and versions on the specification version page. My sense is that there is value in keeping the compatible implementations used the ratify the specification version separate from those that follow, but can easily be convinced otherwise. FWIW, we should have an issue labeled "[certification](https://github.com/eclipse-ee4j/jakartaee-platform/issues?utf8=%E2%9C%93&q=+label%3Acertification+)" for every request for certification of a compatible implementation; maybe that's enough for an historical record.

Regardless, this discussion is out of scope here. I recommend addressing the issue of keeping track of current and historical compatible implementations to the specification committee.

**Comment by bshannon** [comment]
> @bshannon, there are no versions of Papyrus Server is currently listed in the compatible implementations section of the [specification version page](https://github.com/jakartaee/specifications/blob/master/platform/8/_index.md).

Did you mean Payara Server?

It looks like a lot of the compatible implementations have failed to submit a PR to include them in the list.

> The Eclipse Foundation only cares that the Eclipse Foundation Specification Process is followed. How releases are documented is the specification committee's call.
> 
> IMHO, it makes sense to list all compatible products and versions on the specification version page. My sense is that there is value in keeping the compatible implementations used the ratify the specification version separate from those that follow, but can easily be convinced otherwise. FWIW, we should have an issue labeled "[certification](https://github.com/eclipse-ee4j/jakartaee-platform/issues?utf8=%E2%9C%93&q=+label%3Acertification+)" for every request for certification of a compatible implementation; maybe that's enough for an historical record.
> 
> Regardless, this discussion is out of scope here. I recommend addressing the issue of keeping track of current and historical compatible implementations to the specification committee.

What is Eclipse planning to do for the Compatible Products page?  List all, or just list the latest?

I'll move the more general discussion about the specification pages to the specification committee.

**Comment by ivargrimstad** [comment]
Accepted by lazy consensus
