### ISSUE TITLE
Is there any plan to update the xml namespace in the spec descriptor file?

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-platform#142]
Due to some historical reasons, the XML namespace is changed to jcp.org from sun.com. I saw there is some work to change the codes package prefix to `jakartaee.` in  Jakarta EE 9. Is there some plan to change the XML namespace in the deployment descriptor of the specs.

1. web.xml(Servlet)
2. ejb-jar.xml Ejb
3. persistence.xml, orm.xml( JPA)
4. faces-config.xml, and facelets.xhtml (JSF)
5. beans.xml, CDI
etc.

**Comment by kwsutter** [comment]
Yes.  This was discussed on the Platform call yesterday morning.  @ivargrimstad is working with the Eclipse Foundation to find an appropriate location within the Eclipse infrastructure.  And, we already have Issue #45.  So, once we get the location figured out, then we'll use #45 to do the actual work.  If you are interested in helping out, you are welcome to watch that issue to see when we're ready for the code changes.  Thanks!

**Comment by hantsy** [comment]
Great! thanks @kwsutter
