### ISSUE TITLE
Compatibility certification request for Red Hat JBoss Enterprise Application Platform for Web Profile

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#147]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
Red Hat, https://www.redhat.com

- [x] Product Name, Version and download URL (if applicable):<br/>
Red Hat JBoss Enterprise Application Platform, 7.3.0.GA, http://www.redhat.com/en/technologies/jboss-middleware/application-platform

- [x] Specification Name, Version and download URL:<br/>
Jakarta EE Platform, 8, https://jakarta.ee/specifications/platform/8/

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip)
`14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`

- [x] Public URL of TCK Results Summary:<br/>
[TCK Results](https://github.com/RedHatOfficial/jbosseap-certifications/blob/EE8/EAP-7.3.0/jakarta-web-profile.adoc#tck-results)

- [x] Any Additional Specification Certification Requirements:<br/>

Jakarta Dependency Injection 1.0 TCK:
[jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
`b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`

Jakarta Contexts and Dependency Injection 2.0 TCK:
[cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)
`75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`

Jakarta Bean Validation 2.0 TCK:
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
`b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`

- [x] Java runtime used to run the implementation:<br/>
Oracle JDK 1.8.0_191

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS version: [Red Hat Enterprise Linux Server 7.4 (Maipo)](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux) 
Database version: Apache Derby Network Server 10.14.2.0
Database JDBC Driver and version: Apache Derby 10.14.2.0

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bshannon** [comment]
I don't know why this wasn't closed when it was marked Accepted, but I'll close it now.
