### ISSUE TITLE
Create a "Backwards Compatibility" section in the Platform spec

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#154]
**Is your feature request related to a problem? Please describe.**
Based on the discussion of today's Platform Call, we want a new section in the Platform Spec that describes what needs to be performed for Backwards Compatibility.  For example, we discussed the need to change the existing `javax.` properties to `jakarta.*` properties.  For those implementations that wish to provide backwards compatibility with Jakarta EE 8, they would need to support both flavors.

**Describe the solution you'd like**
A new section.

**Describe alternatives you've considered**
We need a permanent location to document these type of scenarios.  The Platform spec is the logical location.

**Comment by hantsy** [comment]
I hope there is a fork of https://github.com/apache/tomcat-jakartaee-migration to describe how to migrate to Jakarta EE 9 from Jakarta EE 8 without any code changes. 

Besides, I am not sure if possible to provide a NetBeans plugin to do the same job in IDE when detecting the Jakarta EE 9 dependencies is presented in compile classpaths but codes were written in Jakarta EE 8.

**Comment by kwsutter** [comment]
The overarching goals of backward compatibility were laid out here:  https://eclipse-ee4j.github.io/jakartaee-platform/CompatibilityRequirements

Due to the `jakarta` namespace change in Jakarta EE 9, some of those goals were not achievable.  I will propose a PR with a (hopefully) brief chapter on backwards compatibility.

**Comment by kwsutter** [comment]
PR #260 should eventually resolve this issue.
