### ISSUE TITLE
Compatibility certification request for JEUS 8.5 for Full Platform

### ISSUE THREAD

**Issue by TmaxEE** [eclipse-ee4j/jakartaee-platform#156]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [TmaxSoft Co., Ltd](https://www.tmaxsoft.com/) <br/><br/>
- [x] Product Name, Version and download URL (if applicable):<br/>
  [JEUS 8.5](https://kr.tmaxsoft.com/jakee/jeus8-b266.zip) <br/><br/>
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, 8, Full Platform](https://jakarta.ee/specifications/platform/8/)<br/><br/>
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform CTS 8.0.2](https://download.eclipse.org/jakartaee/platform/8/jakarta-jakartaeetck-8.0.2.zip) , SHA-256: <code> 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965</code> <br/><br/>
- [x] Public URL of TCK Results Summary:<br/>
  [https://kr.tmaxsoft.com/jakee/JEUS8.5_Full_Profile_Certification_Summary.html](https://kr.tmaxsoft.com/jakee/JEUS8.5_Full_Profile_Certification_Summary.html) <br/><br/>
- [x] Any Additional Specification Certification Requirements:<br/><br/>
  * Jakarta Dependency Injection 1.0 TCK
    Download URL & SHA-256:<br/> [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), <code> b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f</code><br/><br/>
  * Jakarta Contexts and Dependency Injection 2.0 TCK
    Download URL & SHA-256:<br/> [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip), <code> 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808</code><br/><br/>
  * Jakarta Bean Validation 2.0 TCK
    Download URL & SHA-256: [beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), <code> b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974</code><br/><br/>
- [x] Java runtime used to run the implementation:<br/>
  OracleJDK Java(TM) SE Runtime Environment (build 1.8.0_231-b11) <br/><br/>
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Red Hat Enterprise Linux Server release 6.3 (Santiago) <br/><br/>
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by scottmarlow** [comment]
Minor type, Full Profile, should be changed to Full Platform.

**Comment by TmaxEE** [comment]
> Minor typo, Full Profile, should be changed to Full Platform.

fixed. thank you.

**Comment by ivargrimstad** [comment]
+1
LGTM

**Comment by TmaxEE** [comment]
Since JEUS 8 is certified for JavaEE 7, we decided to name this new product as JEUS 9 to be certified for Jakarta EE 8. May I change the name of the product in this certification request?

**Comment by bshannon** [comment]
> Since JEUS 8 is certified for JavaEE 7, we decided to name this new product as JEUS 9 to be certified for Jakarta EE 8. May I change the name of the product in this certification request?

You should be able to edit your original submission.  Click on the three dots and select "Edit".

**Comment by kwsutter** [comment]
Was renaming the product identifier the only change?  Or, did you generate new binaries?  If you have new binaries, then you would need to ensure that your test results were properly executed against your updated binaries.

Other than that, the rest of the certification request looks good.

**Comment by TmaxEE** [comment]
Sorry for the confusion, but if we need to retest, we'll just decide to get certified with JEUS 8.5. We want to proceed as is without changing the name of the product.

**Comment by ivargrimstad** [comment]
Approved by lazy consensus.

**Comment by dblevins** [comment]
@TmaxEE Could you possibly fill out the JEUS tab of this spreadsheet?  See the TomEE and Payara tabs for reference.  This is not related to your certification request, I just didn't know how else to contact you :) https://docs.google.com/spreadsheets/d/1xiC14jnuGA8FjWtooJEgHxtzSF5OilrdhyTSSH4S154/edit#gid=244450662
