### ISSUE TITLE
Compatibility certification request for Payara Server 5.201 for Full Platform

### ISSUE THREAD

**Issue by Pandrex247** [eclipse-ee4j/jakartaee-platform#159]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Payara Services Ltd.](https://www.payara.fish/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Payara Server 5.201](https://www.payara.fish/software/downloads/)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
   [Jakarta EE Platform CTS 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip), SHA-256:
`14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
- [x] Public URL of TCK Results Summary:<br/>
  https://docs.payara.fish/jakartaee-certification/5.201/tck-results-full-5.201.html
- [x] Any Additional Specification Certification Requirements:<br/>

  * Jakarta Dependency Injection 1.0 TCK
     Download URL & SHA-256:
     [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), 
     `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  * Jakarta Contexts and Dependency Injection 2.0 TCK
     Download URL & SHA-256:
     [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip), 
     `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  * Jakarta Bean Validation 2.0 TCK,
     See test results in section beanvalidation.
     Download URL & SHA-256:
     [beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), 
     `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`
- [x] Java runtime used to run the implementation:<br/>
OpenJDK 8u242 (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
Linux Ubuntu 18.04 LTS
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1

**Comment by ivargrimstad** [comment]
Accepted by lazy consensus
