### ISSUE TITLE
java-module.java Allowed contents for Jakarta EE 9

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#162]
While looking at the jakarta.persistence:jakarta.persistence-api:3.0.0-RC1 API jar available from
https://repo1.maven.org/maven2/jakarta/persistence/jakarta.persistence-api/3.0.0-RC1/jakarta.persistence-api-3.0.0-RC1.jar

It was noticed that it contained a module-info.class that contains potentially unwanted dependencies:

```
module jakarta.persistence {

    requires java.logging;
    requires transitive java.instrument;
    requires transitive java.sql;

    exports jakarta.persistence;
    exports jakarta.persistence.criteria;
    exports jakarta.persistence.metamodel;
    exports jakarta.persistence.spi;

    uses jakarta.persistence.spi.PersistenceProvider;
}
```

An issue was raised in the jpa-api project to question this:
https://github.com/eclipse-ee4j/jpa-api/issues/264

but the issue for the platform project is what guidelines do we need to document for the Jakarta EE 9 release?

**Comment by bshannon** [comment]
These additional types are part of the JPA API so they need to be declared in
the module-info.

I hate to go down the rat hole of fully defining guidelines for module-info for
this release, but it may be inevitable.  I just think we have to allow that the
guidelines might change later in an incompatible way as we more to adding
module support to the specs.

**Comment by kwsutter** [comment]
Module naming conventions are being added to the Platform spec via PR #262.
