### ISSUE TITLE
Compatibility certification request for Primeton AppServer for Full Platform

### ISSUE THREAD

**Issue by jxtaliu** [eclipse-ee4j/jakartaee-platform#171]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Primeton Information Technologies, Inc](http://www.primeton.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Primeton AppServer, V7](http://primeton.com/products/pas/)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip)
  `14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results](http://primeton.com/products/pas/tck_results/EE8-jakarta-full-platform-V7.html)
- [x] Any Additional Specification Certification Requirements:<br/>
  [Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
  `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  [Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)
  `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  [Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
  `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`
- [x] Java runtime used to run the implementation:<br/>
  openjdk version "1.8.0_242"
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  OS version: CentOS Linux release 7.2.1511 (Core)
  Database version: Apache Derby Network Server 10.14.2.0
  Database JDBC Driver and version: Apache Derby 10.14.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1 
LGTM

**Comment by carlosdlr** [comment]
+1
LGTM

**Comment by ederks85** [comment]
+1
LGTM

**Comment by smillidge** [comment]
+1

**Comment by kwsutter** [comment]
I don't believe this Certification Request was left open long enough for the lazy consensus to kick in.  It needed to be left open for 14 days according to [our process](https://jakarta.ee/committees/specification/tckprocess/).  And, given the world situation, a bit more allowed time is probably in order...

Given all of that, I still will cast my +1 vote in favor of this Certification Request.  Thanks.

**Comment by kwsutter** [comment]
Sorry to be a pain in the rear on process, but we really shouldn't rush these through.  If I am reading our process incorrectly, I will gladly be corrected.  Otherwise, I am going to re-open this Issue and remove the Accepted label for now.  Thanks.

**Comment by kwsutter** [comment]
Plenty of time has passed now for the lazy consensus process to complete.  I've added the `accepted` label and will now close this Issue.  Thanks for your patience.
