### ISSUE TITLE
Compatibility certification request for Apusic AAS  for Full Platform

### ISSUE THREAD

**Issue by PatrickHuang888** [eclipse-ee4j/jakartaee-platform#175]
- [&check; ]  Organization Name ("Organization") and, if applicable, URL:<br/>
  [Kingdee Apusic Cloud Computing](http://www.apusic.com)
- [&check;] Product Name, Version and download URL (if applicable):<br/>
   [AAS 10.1](http://www.apusic.com/wp-content/uploads/AAS-V10.zip)
- [&check;] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)
- [&check; ] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform CTS 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) , SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
- [&check; ] Public URL of TCK Results Summary:<br/>
[https://github.com/apusic/aas-tck/blob/master/aas_10_1_tck_results.md](https://github.com/apusic/aas-tck/blob/master/aas_10_1_tck_results.md)

- [&check; ] Any Additional Specification Certification Requirements:<br/>
Jakarta Dependency Injection 1.0 TCK

See test results in section di.
Download URL & SHA-256: [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f

Jakarta Contexts and Dependency Injection 2.0 TCK

See test results in section cdi.
Download URL & SHA-256: [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip), SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808

Jakarta Bean Validation 2.0 TCK,

See test results in section beanvalidation.
[beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), SHA-256: b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974

Jakarta Batch 1.0 TCK tests are included in Jakarta EE 8 CTS tests, See test results in section jbatch

- [&check; ] Java runtime used to run the implementation:<br/>
OracleJDK Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
- [&check; ] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
Ubuntu 18.04.4 LTS (Bionic Beaver)
Apache Derby 10.14.2.0 
- [&check;] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [&check; ] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ivargrimstad** [comment]
Accepted by lazy consensus after 14 days
