### ISSUE TITLE
Compatibility certification request for Oracle Web Logic 14.1.1.0 for Full Platform

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#176]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Oracle, Inc. ](https://www.oracle.com)

- [x] Product Name, Version and download URL (if applicable):<br/>
 [Oracle Web Logic Server, 14.1.1.0.0](https://www.oracle.com/middleware/technologies/weblogic-server-installers-downloads.html)

- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, 8.0](https://jakarta.ee/specifications/platform/8/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform CTS 8.0 (8.0.2)](https://download.eclipse.org/jakartaee/platform/8/jakarta-jakartaeetck-8.0.2.zip), SHA-256: `14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`

- [x] Public URL of TCK Results Summary:<br/>
  [Jakarta EE 8 Platform TCK Result summary](https://www.oracle.com/middleware/technologies/jakartaee_report.html)

- [x] Any Additional Specification Certification Requirements:<br/>
 
- [Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip), SHA-256: `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
- [Jakarta Contexts and Dependency Injection 2.0 (2.0.6) TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip), SHA-256: `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
- [Jakarta Bean Validation 2.0 (2.0.5) TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip), SHA-256: `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`
- Jakarta Batch 1.0 TCK tests are included in Jakarta EE 8 CTS tests, See [CTS 8 results, Stage Name: jbatch](https://www.oracle.com/middleware/technologies/jakartaee_report.html#JakartaJBatch)
- [Jakarta Debugging Support for Other Languages 1.0 TCK](https://download.eclipse.org/jakartaee/debugging/1.0/eclipse-debugging-tck-1.0.0.zip), SHA-256: `c15d41a6d34c844d34ea846bd0ed6b5baa0d85cbfc3d05209e4df955ef7a5df7`

- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_251
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby 10.14.2.0, Oracle Linux 7

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ivargrimstad** [comment]
Accepted by lazy consensus after 14 days.

**Comment by jackeymason** [comment]
Hi Ed,
I didn't see Oracle 14c on the Jakarta EE Compatible Products page.
I assume it is compatible based upon your request here, though I could find no supporting documentation with Oracle.
Could you share with me how I would go about configuring Weblogic 14c to use JPA 3.1 so that I might test this and
migrate from JPA 2 to 3?
Thank you.
Jack Mason

**Comment by ivargrimstad** [comment]
Oracle Weblogic 14c is indeed listed on the [Compatible Products page](https://jakarta.ee/compatibility/).

However, since it is [Jakarta EE 8 Compatible](https://jakarta.ee/compatibility/certification/8/), the supported version of Jakarta Persistence would be [Jakarta Persistence 2.2](https://jakarta.ee/specifications/persistence/2.2/).
