### ISSUE TITLE
Java SE Version Tracing

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jakartaee-platform#2]
Users tend to think that Java EE 8 was the enterprise variant of Java SE 8, so they ask questions like "When will Java EE 9 be there?". Inspired by this, we should discuss if and how we want Jakarta EE major releases be somehow related to Java SE releases. For example, will Jakarte EE 9 mandate the use of Java 9 signature features, will we follow the Java SE pace, and so on.

**Comment by bshannon** [comment]
Yes, that was exactly the intended relationship between Java SE and Java EE.

This question came up previously on the [community mailing list](https://www.eclipse.org/lists/jakarta.ee-community/msg00034.html).
We also discussed this Steering Committee; here's my presentation of the issue:

> A question came up recently on the jakarta.ee-community mailing list
> about the version number of the initial Jakarta EE release. [1]
> 
> So far we've been calling this "Jakarta EE 8" informally as a way of
> indicating that it will be compatible with and based on Java EE 8.
> We should decide explicitly how we want to handle numbering of
> Jakarta EE releases.  This may feel premature since we don't even have
> a Jakarta EE spec process, but I think it's a strategic decision that
> will guide many subsequent decisions and positioning of Jakarta EE.
> 
> It seems to me that there are three obvious choices for how to handle
> version numbers of Jakarta EE:
> 
>     1. Continue the Java EE version numbering approach with Jakarta EE
>        X being based on Java SE X, for all values of X.  With the new
>        rapid release cycles of Java SE, that might mean skipping some
>        version numbers to allow Jakarta EE to stay in sync with Java SE.
> 
>     2. Start with Jakarta EE 8 and increment the version number for
>        each release, making a separate and explicit decision as to what
>        version of Java SE to base each release on.
> 
>     3. Start over with Jakarta EE 1, incrementing the version number
>        for each release.
> 
> The intent with #1 for Java EE was that it presented a consistent view
> of a single Java "platform", that came in several "editions".
> Obviously that's no longer the intent with Jakarta EE.  A side effect
> of this approach was that it made it obvious which version of the Java
> SE APIs could be used by Java EE developers.
> 
> The clear advantage of #2 is that it leverages that initial relationship
> with Java EE while allowing Jakarta EE to proceed on its own path with
> a looser relationship to Java SE.
> 
> The motivation for #3 is to emphasize the break with the past and to
> present Jakarta EE as something new with its own identity.
> 
> Comments?
>
> [1] https://dev.eclipse.org/mhonarc/lists/jakarta.ee-community/msg00034.html

The clear consensus in the Steering Committee was option #2 above.
I think we should close out this issue accordingly.

**Comment by chkal** [comment]
I also think that option 2 is a good choice. I don't see a huge value in synchronizing the Jakarta EE version numbers with Java SE.

**Comment by keilw** [comment]
+1 The new licensing models for Java SE may keep many large enterprises on a particular LTS version until it's worth upgrading all their hundreds or thousands of services and servers to a new version. Even with automation and container technology that is not something large companies do every few months just for the sake of it. 
A minimum compatible Java SE version for a particular Jakarta EE version sounds best.

**Comment by kazumura** [comment]
+1 I have many customers who want to use various combinations of Java SE versions and Java EE versions.

**Comment by spullara** [comment]
Shouldn't we dependent on a version of SE that isn't end of lifed? Wouldn't that be Java 11 in this case?

**Comment by mkarg** [comment]
@bshannon Is there a final decision on option #2 meanwhile, hence can we close this issue now?

**Comment by bshannon** [comment]
Yes, option #2 is the decision.

Applying that to Jakarta EE 8, the minimum requirement is Java SE 8, to be compatible with Java EE 8.
