### ISSUE TITLE
Redo images to make them editable (ie. svg)

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#214]
While updating the Platform spec for Milestone 1 of Jakarta EE 9, we determined that many of the images used in the spec need to be edited.  Unfortunately, the current png format is not suitable for easy editing.  We started to experiment using the two diagrams in the Deployment chapter.  We used [inkscape](https://inkscape.org/) to recreate the images in [svg](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) format.  Although it took a little bit of work to recreate them, they are now quite easy to update going forward.

We need to do this with the rest of the images in the Platform spec.  This was documented as a comment in this Specifications PR: https://github.com/jakartaee/specifications/pull/180#issuecomment-645458094

**Comment by kwsutter** [comment]
Specific images that need to be recreated... Can do the others to be complete, but these definitely need updating for Jakarta EE 9...  Let's first recreate them as they currently exist, and then use a separate PR for updating them.

- [ ] JavaEEarchitecture.png
- [ ] JavaEEinteroperability.png

**Comment by cpusam** [comment]
I will try make this, but only at Saturday I can do it in my free time. May you wait until there?

**Comment by kwsutter** [comment]
> I will try make this, but only at Saturday I can do it in my free time. May you wait until there?

Absolutely we can wait.  These are not for the Milestone, so we have some time before they are "due".  Looking forward to what you can re-create.  Thanks.

**Comment by cpusam** [comment]
@kwsutter which folder should I pit the images? I make the bigger one and take a lot of time, I will work on the second still today. Maybe today I'll send the two images.

**Comment by cpusam** [comment]
@kwsutter Sorry for the delay to send the images. I was resting today, but the images are now ready. May you review the exported png if it's k? See below:
The exported png of svg javaeearch:
![javaeearch](https://user-images.githubusercontent.com/6283430/85236642-1098d680-b3f6-11ea-8250-ceb9f4d7a90c.png)

The exported png of svg javaeeinter:
![javaeeinter](https://user-images.githubusercontent.com/6283430/85236649-20b0b600-b3f6-11ea-9a85-0b600e4d8c01.png)

**Comment by cpusam** [comment]
Well, I'll give you the svg's for here. I don't want credits ans so, I'll not subcrisbe to eclipse foundation. Take my svg's images and I give you permission to not give me credits, it's a public domain:
[NOTE: I don't have many time so I will post they here]

[JavaEE_svg_images.zip](https://github.com/eclipse-ee4j/jakartaee-platform/files/4818904/JavaEE_svg_images.zip)

**Comment by cpusam** [comment]
The commit with images are ready.

**Comment by kwsutter** [comment]
I just approved and merged PR #217.  Thanks, @cpusam, for redo-ing these images.  They look great.

**Comment by aeiras** [comment]
I have been following this ticket because it brings Contributions to the project without signing any agreements. 
It is formidably fun to see Jakartee Samuel @cpusam contribute without red-tape and use write up authorization to submit designs. 

Love it, you Samuel are worthy of emulation as so are you facilitator Kevin :)

**Comment by cpusam** [comment]
@aeiras 
> Love it, you Samuel are worthy of emulation as so are you facilitator Kevin :)

Oh, thanks! I like of opensource and this is the first time that I used inkscape to contribute with some project :)

**Comment by aeiras** [comment]
wow, that is amazing Samuel! 

Thanks for sharing that.  
Without pressure, please check out the doodle poll open for the Friends of Jakarta zoom call using this thread and if able, participate and join that call. I believe that Jakarta EE benefit from Contributors like you! :) stay safe and hope to continue to learn more about what you care to contribute to and the clever forms you own such contributions. Cheers

https://www.eclipse.org/lists/jakarta.ee-community/msg02313.html

**Comment by cpusam** [comment]
@aeiras I will read that at Saturday, because I'm working now, but, I pretend to redo some others images to svg.
It's a little weird for me contributing with graphics being a programmer hahaha

**Comment by ggam** [comment]
Awesome work Samuel! Perhaps you would also take a look at the Jakarta EE
tutorial images? There are some old graphics there also but we never found
someone that could take care of them.

**Comment by cpusam** [comment]
@ggam sorry for delay to answer. Could you say me where that images are located? At saturday, I will evaluate and estimate the time to do it.

**Comment by ggam** [comment]
But you only took 3 hours to respond haha!!

Images are located at
https://github.com/eclipse-ee4j/jakartaee-tutorial/tree/master/src/main/jbake/assets/img

There are quite a bunch of images (~65) but there's no hurry for getting it
completed. Even if you submit a draft PR with only a few of them, it would
be a great start. I made most of the work to refresh the Tutorial look and
feel (see https://github.com/eclipse-ee4j/jakartaee-tutorial/pull/191) but
we need to convert all the images before officially promoting it.

**Comment by kwsutter** [comment]
This Issue is closed.  Maybe it would be better to continue the Tutorial image request in the Tutorial repo?  Thanks!  @ggam @cpusam
