### ISSUE TITLE
Update Platform Spec due to removal of Distributed Interop

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#220]
We have several TODO's in the Platform Spec relating to the removal of the Orb, Corba, and Distributed Interop.  The areas that I have found that need review and updating are flagged with "**TODO**", so they show up in the generated pdf and html as well as the asciidoc source.

In addition to the text updates, we also need to ensure that the JakartaEEinteroperability.svg image file is properly updated.  (This image rename was performed by PR #219.)

I'm going to assign @dblevins and @cesarhernandezgt to this Issue, but anyone with the proper background on the EJB 4.0 changes can help out.  Thanks!

**Comment by kwsutter** [comment]
Nudge, @dblevins and @cesarhernandezgt.  Looking to close up the Platform Spec in the near future, but we need these updates for the removal of the Distributed Interop.  Your expertise would be appreciated.  Thanks!

**Comment by dblevins** [comment]
@kwsutter Looking.

**Comment by kwsutter** [comment]
One of the sections ("RMI-IIOP (Proposed Optional)" is being worked via PR #249.  More is needed...

**Comment by kwsutter** [comment]
Other PRs that were used to update the Platform Spec due to the removal of Distributed Interop:
PR #255 - Interop Chapter
PR #256 - Platform Overview Chapter
PR #257 - Profiles Chapter

**Comment by kwsutter** [comment]
Since all of the associated PRs are now merged, I'm going to close this Issue.  We can open new issues and/or PRs as warranted.  Thanks.
