### ISSUE TITLE
Compatibility certification request for Open Liberty 20.0.0.3 for Full Platform

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-platform#227]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [IBM Corporation](https://www.ibm.com)

- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 20.0.0.3](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2020-03-05_1433/openliberty-javaee8-20.0.0.3.zip)

- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Full Profile, 8](https://jakarta.ee/specifications/platform/8)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip)
 `14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`

- [x] Public URL of TCK Results Summary:<br/>
  [Test Results](https://openliberty.io/certifications/jakartaee/platform/8/20.0.0.3-TCKResults.html)

- [x] Any Additional Specification Certification Requirements:<br/>
  Jakarta Injection
  [jakarta.inject-tck-1.0-bin.zip](http://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
 `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`

  Jakarta Contexts and Dependency Injection
  [cdi-tck-2.0.7.SP1-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.7.SP1-dist.zip)
 `8c7ed87ac9fcb9c985aefebd653204dc3a83ad9d004a9bfd4d61047ca2f55c85`

  Jakarta Bean Validation
  [beanvalidation-tck-dist-2.0.5.tar.gz](http://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz)
 `05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8`

- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 1.8.0_222 (HotSpot)

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Ubuntu 18.04 LTS, Apache Derby

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

- [x] Relevant challenges & resolution:
  signaturetest, 2 failures
  [eclipse-ee4j/faces-api#1474](https://github.com/eclipse-ee4j/faces-api/issues/1474)

**Comment by kwsutter** [comment]
This looks good to me, @brideck.  But, we should wait for some additional reviewers before going ahead with Acceptance.  I've sent a note to the Platform Dev mailing list asking for a review.  Thanks!

**Comment by ivargrimstad** [comment]
+1
LGTM

**Comment by smillidge** [comment]
+1

**Comment by kazumura** [comment]
+1

**Comment by edbratt** [comment]
I would prefer to see this point directly to the specific product download that has been certified. If there are more than one, perhaps list all the download versions that this certification covers. Otherwise, is it reasonable for users to just pull the 20.0.x with the largest value of x? That might be a logical user assumption. Is it valid?

**Comment by brideck** [comment]
> 
> 
> I would prefer to see this point directly to the specific product download that has been certified.

This is a good point.  I've updated the link.

**Comment by kwsutter** [comment]
Since this Certification Request was approved by multiple Leads of the Platform Project, I'm going to mark this Closed.
