### ISSUE TITLE
Jakarta EE 9 only requires support for schemas from Jakarta EE 8+ (no XSDs or DTDs from earlier than EE 8 are required to be supported)

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#234]
**Describe the bug**
https://jakarta.ee/specifications/platform/9/platform-spec-9-SNAPSHOT.html#a3203 should be updated to not require support of XSDs/DTDs from releases earlier than Jakarta EE 8.

Perhaps a change from:

`
All valid Jakarta EE application deployment descriptors must conform to the XML Schema definition, or the DTD or schema definition from a previous version of this specification. 
`

To:
`
All valid Jakarta EE application deployment descriptors must conform to the XML Schema definition from the Jakarta EE 8+ version of this specification. 
`
Or something better than that is fine. :-)

For reference the [related discussion/vote was summarized here](https://eclipse-ee4j.github.io/jakartaee-platform/minutes/2020-01-28.html).

**Comment by kwsutter** [comment]
Thanks, @scottmarlow.  FYI, in that same paragraph you referenced, there is a reference to the schema section of the App Deployment section:  https://jakarta.ee/specifications/platform/9/platform-spec-9-SNAPSHOT.html#a3447

This much clearer on the support for Jakarta EE 8+ schemas.  But, I think it would still be good to update this section a bit to avoid possible confusion.  I'll do a quick update and reference the PR shortly...

**Comment by kwsutter** [comment]
Should be resolved via PR #236.
