### ISSUE TITLE
Update TCK links on Wiki page...

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#235]
Please replace TCK job links on https://github.com/eclipse-ee4j/jakartaee-platform/wiki/JakartaEE9#tcks with the below jobs.  These jobs aren't running that cleanly currently, in that we get some failures (e.g. GlassFish fails to start for unknown reason) that we work around by retesting individual test groups that failed.  

Platform TCK Build - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-900/

Full Platform TCK Run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/

Web Profile TCK run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-web-900/

Platform TCK Standalone build/run - Platform TCK Build - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-900

Full Platform TCK Run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900

Web Profile TCK run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-web-900

Platform TCK Standalone build/run - https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900

CC @alwin-joseph

**Comment by starksm64** [comment]
Thanks, I have added these to the wiki

**Comment by alwin-joseph** [comment]
I think the links was copied twice. Just putting the links here again also adding few others.

All the below jobs uses or builds eft licensed TCK bundles.

Platform TCK Build - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-build-900/

Full Platform TCK Run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/

Web Profile TCK run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-web-900/

Standalone TCKs(only the ones built from jakartaee-tck repo) build + run - https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900

(All the above *run* jobs are parameterised to run a subset of the suites or tcks hence green doesn't always mean clean run)

jaxb-tck build + run - https://ci.eclipse.org/jakartaee-tck/job/eftl-jaxb-tck-build-run

mail-tck build + run - https://ci.eclipse.org/mail/job/eftl-mailtck-build-run

activation-tck build + run - https://ci.eclipse.org/jaf/job/eftl-activationtck-build-run

**Comment by kwsutter** [comment]
Wiki has been updated, closing this Issue.  Thanks, @scottmarlow and @alwin-joseph.
