### ISSUE TITLE
Please remove jts-dev@eclipse.org from https://jakarta.ee/connect/mailing-lists

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#242]
**Describe the bug**
https://jakarta.ee/connect/mailing-lists contains jts-dev which is a `The JTS Topology Suite is a Java library for creating and manipulating vector geometry. It also provides a comprehensive set of geometry test cases, and the TestBuilder GUI application for working with and visualizing geometry and JTS functions.` that is not related to OTS or JTS (see ^ description on https://github.com/locationtech/jts).

Please remove jts-dev@eclipse from https://jakarta.ee/connect/mailing-lists

**Comment by kwsutter** [comment]
This Issue needs to be against this repository:  https://github.com/jakartaee/jakarta.ee 

But, I don't seem to have the authority to transfer it.  @scottmarlow, can you transfer it?  If not, maybe @ivargrimstad?

**Comment by scottmarlow** [comment]
Thanks @kwsutter , I will open a new issue under https://github.com/jakartaee/jakarta.ee

**Comment by scottmarlow** [comment]
The new issue is https://github.com/jakartaee/jakarta.ee/issues/885
