### ISSUE TITLE
Compatibility certification request for FJ-EAP 1.0.0 for Full Platform

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/jakartaee-platform#244]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Fujitsu Limited](https://www.fujitsu.com/jp/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  FUJITSU Software Enterprise Application Platform 1.0.0  
- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  Jakarta EE Platform CTS 8.0.2  
  Download URL: `https://download.eclipse.org/jakartaee/platform/8/jakarta-jakartaeetck-8.0.2.zip`  
  SHA-256: `14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap100-ee8full-tck-results/)
- [x] Any Additional Specification Certification Requirements:<br/>
  * Jakarta Dependency Injection 1.0 TCK  
    Download URL: `https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip`  
    SHA-256: `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
  * Jakarta Contexts and Dependency Injection 2.0 TCK  
    Download URL: `https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip`  
    SHA-256: `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`
  * Jakarta Bean Validation 2.0 TCK  
    Download URL: `https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip`  
    SHA-256: `b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974`
- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 1.8.0_265-b01
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  CentOS Linux 7.3, Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM +1

**Comment by smillidge** [comment]
+1

**Comment by keilw** [comment]
+1

**Comment by kwsutter** [comment]
@kazumura, Is there a download URL for your product?  Other than that, it looks good.

**Comment by kazumura** [comment]
No. We don't have the direct link URL right now.

**Comment by hs536** [comment]
@kwsutter As @kazumura pointed out, we don't have the download URL for our product now.
Is there anything else we can do for the certification process?

**Comment by hs536** [comment]
Please be informed that the URL for the TCK results page, which is referenced in this CCR, has been updated due to a change in our company's website policy.

Public URL of TCK Results Summary:
- before: https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap100-ee8full-tck-results/index.html
- after: https://docs.fujitsu/documents/002474/eap100-ee8full-tck-results.pdf

**Comment by ivargrimstad** [comment]
No problem. Would you please file an issue to update the link from the compatibility page here https://github.com/jakartaee/jakarta.ee/issues
