### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 6.0 for Jakarta EE Platform, 9.0

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#258]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation

- [x] Product Name, Version and download URL (if applicable):<br/>
  - [Eclipse GlassFish 6.0](https://eclipse-ee4j.github.io/glassfish/download)
  - [Eclipse GlassFish 6.0-RC2](https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-RC2.zip)

- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, 9](https://jakarta.ee/specifications/platform/9/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  - [jakarta-jakartaeetck-9.0.0.zip](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0.zip)
  - SHA-256: `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392`

- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/9.0/TCK-Results)

- [x] Any Additional Specification Certification Requirements:<br/>
  None

- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby, Linux, Centos 7

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kazumura** [comment]
DI, CDI, BV are need to add to "Any Additional Specification Certification Requirements:" section.

**Comment by scottmarlow** [comment]
>     * [x]  TCK Version, digital SHA-256 fingerprint and download URL:
>       
>       * [Jakarta EE Platform TCK 9.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jakartaeetck-9.0.0.zip)

@edbratt please update to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0.zip which has the fixed Platform TCK PDF (thanks @alwin-joseph for fixing that!)  The updated SHA from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaee-tckinfo.txt is `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392`.

Please update the SHA in the following with `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392`
>       * SHA-256: `661752b5c6c2e058b9ddb21b1ffbb36f9e99ad11fd51b8aa61bd10d6c235d308`
> 
>     * [ ]  Public URL of TCK Results Summary:
>       [TCK Results](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/9.0/TCK-Results)
>

**Comment by edbratt** [comment]
TCK Summary updated with https://github.com/eclipse-ee4j/glassfish/pull/23271

**Comment by kwsutter** [comment]
@edbratt, shouldn't the TCK link be the RC1 version of the TCK?

**Comment by edbratt** [comment]
I don't think so. I would expect this request to be against the final TCK. TCK Team pushed their proposed final TCK without change from RC1 -- so, in fact they are the same, but both copies exist and I would expect the final TCK to be pushed to the Specification download repository. If the TCK changes, we will need to update the SHA codes for this and the TCK Summary.

**Comment by kwsutter** [comment]
LGTM!  Thanks, @edbratt!

**Comment by kwsutter** [comment]
@edbratt, if desired...
- [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.

**Comment by edbratt** [comment]
>     * The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.

Done
