### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 6, Web Profile for Jakarta EE 9, Web Profile

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#259]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation

- [x] Product Name, Version and download URL (if applicable):<br/>
  - [Eclipse GlassFish 6.0](https://eclipse-ee4j.github.io/glassfish/download)
  - [Eclipse GlassFish 6.0 Web Profile RC2](https://download.eclipse.org/ee4j/glassfish/web-6.0.0-RC2.zip)

- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform 9, Web Profile](https://jakarta.ee/specifications/webprofile/9/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  - [jakarta-jakartaeetck-9.0.0.zip](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0.zip)
  - SHA-256: `75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392`

- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-web-profile/9.0/TCK-Results)

- [x] Any Additional Specification Certification Requirements:<br/>
  None

- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby, Linux, Centos 7

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
TCK summary updated with https://github.com/eclipse-ee4j/glassfish/pull/23271

**Comment by kwsutter** [comment]
> TCK summary updated with [eclipse-ee4j/glassfish#23271](https://github.com/eclipse-ee4j/glassfish/pull/23271)

@edbratt Shouldn't the [TCK Results](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-web-profile/9.0/TCK-Results) be referencing RC1 of the TCK?  It's still pointing at the non-RC1 version.  Since they have the same SHA in the promoted directory, maybe it doesn't make a lot of difference.  But, it would be clearer if that TCK Results page was updated.  Thanks.

**Comment by kwsutter** [comment]
> > TCK summary updated with [eclipse-ee4j/glassfish#23271](https://github.com/eclipse-ee4j/glassfish/pull/23271)
> 
> @edbratt Shouldn't the [TCK Results](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-web-profile/9.0/TCK-Results) be referencing RC1 of the TCK? It's still pointing at the non-RC1 version. Since they have the same SHA in the promoted directory, maybe it doesn't make a lot of difference. But, it would be clearer if that TCK Results page was updated. Thanks.

Never mind.  I see that I posted a similar comment to the Platform CR yesterday...  Your explanation is fine.  As long as we haven't changed the SHA values, then either reference should be okay.  Thanks.

**Comment by kwsutter** [comment]
LGTM!  Thanks, @edbratt!

**Comment by kwsutter** [comment]
@edbratt, if desired...
- [ ] The compatible implementation project/vendor MUST send an email to tck@eclipse.org for approval of the compatible implementation for trademark usage.

**Comment by edbratt** [comment]
>  The compatible implementation project/vendor MUST send an email to [tck@eclipse.org](mailto:tck@eclipse.org) for approval of the compatible implementation for trademark usage.

Done
