### ISSUE TITLE
Compatibility certification request for IBM WebSphere Liberty for Jakarta EE 8, Web Profile

### ISSUE THREAD

**Issue by NottyCode** [eclipse-ee4j/jakartaee-platform#264]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [IBM Corporation](https://www.ibm.com)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [IBM WebSphere Liberty 20.0.0.3](https://www.ibm.com/support/fixcentral/swg/selectFixes?parent=ibm%7EWebSphere&product=ibm/WebSphere/WebSphere+Liberty&release=20.0.0.3&platform=All&function=fixId&fixids=wlp-webProfile8-20.0.0.3&includeSupersedes=0)  
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform Web Profile 8](https://jakarta.ee/specifications/webprofile/8)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) `14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](https://www.ibm.com/cloud/websphere-liberty/profile-tckresults)
- [x] Any Additional Specification Certification Requirements:<br/>
* Jakarta Contexts and Dependency Injection [cdi-tck-2.0.7.SP1-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.7.SP1-dist.zip) `8c7ed87ac9fcb9c985aefebd653204dc3a83ad9d004a9bfd4d61047ca2f55c85`
* Jakarta Bean Validation [beanvalidation-tck-dist-2.0.5.tar.gz](http://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz) `05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8`
* Direct Injection [jakarta.inject-tck-1.0-bin.zip](http://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip) `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`
- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 8 + HotSpot (jdk8u222-b10)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby, Linux, Ubuntu 18.04
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.
- [x] Relevant challenges & resolution:
  signaturetest, 2 failures
  [eclipse-ee4j/faces-api#1474](https://github.com/eclipse-ee4j/faces-api/issues/1474)

**Comment by ivargrimstad** [comment]
LGTM
+1

**Comment by kazumura** [comment]
+1
