### ISSUE TITLE
Compatibility certification request for Eclipse Glassfish 6.0 for Enterprise Beans 4.0 (part of Jakarta EE 9)

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jakartaee-platform#269]
- [X] Organization Name ("Organization") and, if applicable, URL:<br/>
 Eclipse Foundation
- [X] Product Name, Version and download URL (if applicable):<br/>
 [Eclipse Glassfish 6.0 RC2](https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-RC2.zip)
- [X] Specification Name, Version and download URL:<br/>
[Enterprise Beans 4.0](https://jakarta.ee/specifications/enterprise-beans/4.0/)
- [X] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE 9 TCK RC1](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0-RC1.zip)

SHA-256: 75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392
- [X] Public URL of TCK Results Summary:<br/>
[TCK Result Summary](https://glassfish.org/certifications/jakarta-enterprise-beans/4.0/TCK-Results)
- [X] Any Additional Specification Certification Requirements:<br/>
  None
- [X] Java runtime used to run the implementation:<br/>
Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
None
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
I think this Certification Request should be filed against the ejb-api repository, not the platform.  We already have the overall Glassfish CRs for the Platform and Web Profile.  I believe you want this against the EJB project.

**Comment by jeanouii** [comment]
Moving the issue to ejb-api repo
