### ISSUE TITLE
Nits in Managed Beans 2.0 Specification Doc.

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#273]
Two small comments from reading Managed Beans 2.0 
1) Section 2 -- Consider revising the link to CDI/JSR299 to Jakarta Contexts and Dependency Injection (Jakarta CDI) w/o JSR ID.
2) Section 2.1.2 -- typo in code block, escape back-slash appears in "public class ShoppingCart { ... }"

**Comment by kwsutter** [comment]
Thanks, @edbratt!  Will get this corrected after Managed Beans 2.0 goes final...

**Comment by ederks85** [comment]
PR provided in https://github.com/eclipse-ee4j/managed-beans-spec/pull/2

**Comment by ivargrimstad** [comment]
Closed by eclipse-ee4j/managed-beans-spec#2
