### ISSUE TITLE
Increase the flexibility of platform spec language regarding Java SE compatibility

### ISSUE THREAD

**Issue by bstansberry** [eclipse-ee4j/jakartaee-platform#287]
**Is your request related to a problem? Please describe.**

Section 6.1.1 of the platform spec indicates that it's the intent of the EE project that implementors be able to provide implementations that run on Java SE versions later than SE 8:

"The containers provide all application components with at least the Java Platform, Standard Edition, v8 (Java SE) APIs. Containers may provide newer versions of the Java SE platform, provided they meet all the Jakarta EE platform requirements."

With EE 9.1 work is being done to allow the TCK to be run on SE 11, thus making it possible to not only let users run on SE 11 (as many EE implementors have long done) but also to certify those implementations are EE compatible.

However the platform specification still includes language that can have the effect of restricting implementations to EE 8.

**Describe the solution you'd like**

Identify places in the platform spec that imply SE 8 must be used and replace with more flexible language.

In particular clarify that a certified implementation only needs to provide SE APIs from the SE version(s) that they certify, and that any APIs that are removed in SE since SE 8 are not required unless specifically called out in the platform spec or one of the API specs.

A nice to have would be that such language would be written to make it easy to update for future spec versions that may base on a minimum SE later than 8.

**Additional context**

Following are parts of the platform spec that imply SE 8 must be used:

2.4.1. Container Requirements

"This specification requires that containers provide a Java CompatibleTM runtime environment, as defined by the Java Platform, Standard Edition, v8 specification (Java SE)"

6.1.1. Java Compatible APIs

"In particular, the applet execution environment must be Java SE 8 compatible."

8.3 Class Loading Requirements

Each of the following subsections includes a discussion of what APIs must be made available to components by the container. They all include in their list of required API the item "All Java SE 8 API classes."

8.3.1. Web Container Class Loading Requirements
8.3.2. Jakarta Enterprise Beans Container Class Loading Requirements
8.3.3. Application Client Container Class Loading Requirements

Also, 8.3.4. Applet Container Class Loading Requirements says "The requirements for the applet container are completely specified by the Java SE 8 specification."  This doesn't explicitly require SE 8 but someone might interpret it that way.

9.5. Requirements for All Jakarta EE Profiles

"The Java Platform, Standard Edition 8 is the required API foundation for any Jakarta EE profile."

**Comment by bstansberry** [comment]
@kwsutter FYI.

I didn't get into the required SE source/target level aspects here but as I look into proposed changes if it seems like that discussion would fit well with what I come up with I'll comment back here to propose amending the scope of this issue.

**Comment by kwsutter** [comment]
@bstansberry, Thanks for starting to document this conversation.  I'll add my two cents worth on each of the references you found...

> Following are parts of the platform spec that imply SE 8 must be used:
> 
> 2.4.1. Container Requirements
> 
> "This specification requires that containers provide a Java CompatibleTM runtime environment, as defined by the Java Platform, Standard Edition, v8 specification (Java SE)"

This section was the subject of the previous PR #178 that I recently closed due to this Issue.  This statement implies that a Java runtime compliant with the Java TCK (JCK) not only is required, but also needs to be provided with a Jakarta EE implementation.  This is overreaching (imho).  If we want to require a Java Compatible (TM) runtime for TCK testing, that's one thing.  But, to require that a Java Compatible (TM) runtime needs to be provided (shipped) with Jakarta EE Implementation is too much.

We could change this to say something like, "This specification requires that containers test compliance with a Java Compatible(TM) runtime environment."  Or, as my other PR simplified even further...  "This specification requires that containers test compliance with a Java (TM) runtime environment."

> 
> 6.1.1. Java Compatible APIs
> 
> "In particular, the applet execution environment must be Java SE 8 compatible."

I don't think this is all that bad.  The execution environment implies that it must support Java SE 8 class files.  That's how I read it.  And, since we're still building at the Java SE 8 class level, aren't we okay with this wording?

(got interrupted, will add more text shortly...)

> 
> 8.3 Class Loading Requirements
> 
> Each of the following subsections includes a discussion of what APIs must be made available to components by the container. They all include in their list of required API the item "All Java SE 8 API classes."
> 
> 8.3.1. Web Container Class Loading Requirements
> 8.3.2. Jakarta Enterprise Beans Container Class Loading Requirements
> 8.3.3. Application Client Container Class Loading Requirements
> 
> Also, 8.3.4. Applet Container Class Loading Requirements says "The requirements for the applet container are completely specified by the Java SE 8 specification." This doesn't explicitly require SE 8 but someone might interpret it that way.
> 
> 9.5. Requirements for All Jakarta EE Profiles
> 
> "The Java Platform, Standard Edition 8 is the required API foundation for any Jakarta EE profile."

**Comment by bstansberry** [comment]
@kwsutter 
> @bstansberry, Thanks for starting to document this conversation. I'll add my two cents worth on each of the references you found...
> 

Thanks, Kevin.

> > Following are parts of the platform spec that imply SE 8 must be used:
> > 2.4.1. Container Requirements
> > "This specification requires that containers provide a Java CompatibleTM runtime environment, as defined by the Java Platform, Standard Edition, v8 specification (Java SE)"
> 
> This section was the subject of the previous PR #178 that I recently closed due to this Issue. This statement implies that a Java runtime compliant with the Java TCK (JCK) not only is required, but also needs to be provided with a Jakarta EE implementation. This is overreaching (imho). If we want to require a Java Compatible (TM) runtime for TCK testing, that's one thing. But, to require that a Java Compatible (TM) runtime needs to be provided (shipped) with Jakarta EE Implementation is too much.
> 
> We could change this to say something like, "This specification requires that containers test compliance with a Java Compatible(TM) runtime environment." Or, as my other PR simplified even further... "This specification requires that containers test compliance with a Java (TM) runtime environment."
> 

+1

I suspect the intent of the existing language wasn't that vendors ship a JDK,  but more that an EE container (typically implemented as a single process) provides one at runtime; i.e. that process provides a Java [Compatible] (TM) runtime environment. But a reader of the spec is going to naturally think 'provide' means 'ship'. Saying you have to test on a Java (TM) runtime environment seems like it addresses the basic concern in a less confusing way.

> > 6.1.1. Java Compatible APIs

I missed one in this section:

"The containers provide all application components with at least the Java Platform, Standard Edition, v8 (Java SE) APIs."

> > "In particular, the applet execution environment must be Java SE 8 compatible."
> 
> I don't think this is all that bad. The execution environment implies that it must support Java SE 8 class files. That's how I read it. And, since we're still building at the Java SE 8 class level, aren't we okay with this wording?
> 

This would be a scope expansion for this issue but reading the rest of this paragraph it makes me wonder if the entire concept of the applet container should be dropped from the platform spec.

"Since typical browsers don’t yet provide such support, Jakarta EE products may make use of the Java Plugin to provide the required applet execution environment. Use of the Java Plugin is not required..."

The Java Plugin was removed from JDK 11, so that text is does not fit in a spec oriented toward 11. Further, browsers now go out of their way to discourage use of applets.  The language above also has the problematic use of the word 'provide' we discussed re section 2.4.1 above. (Section 2.4.1 itself also discusses the Java Plugin.)

Reading the spec I don't see anything in it that says what an applet container is meant to do; just a bunch of places where it says it doesn't have to do something.

> > 8.3 Class Loading Requirements
> > Each of the following subsections includes a discussion of what APIs must be made available to components by the container. They all include in their list of required API the item "All Java SE 8 API classes."
> > 8.3.1. Web Container Class Loading Requirements
> > 8.3.2. Jakarta Enterprise Beans Container Class Loading Requirements
> > 8.3.3. Application Client Container Class Loading Requirements
> 
> I wonder if we could just use something like "All Java SE 8 API classes, at a minimum." Might not be 100% complete, but it would get us going in the right direction.

This gets at the main thrust I had in mind for this issue. JDK 11 does not provide all Java SE 8 API classes, e.g. javax.remote. If an EE 9.1 server is running on JDK 11, then the server would have to provide those classes.

> 
> > Also, 8.3.4. Applet Container Class Loading Requirements says "The requirements for the applet container are completely specified by the Java SE 8 specification." This doesn't explicitly require SE 8 but someone might interpret it that way.
> 
> True, but that's a fine line. I really don't know... Are these applet container requirements still spelled out in newer Java SE specifications? Maybe can just drop the "8"?

Or drop applet. :)

> 
> > 9.5. Requirements for All Jakarta EE Profiles
> > "The Java Platform, Standard Edition 8 is the required API foundation for any Jakarta EE profile."
> 
> For now, this is still the requirement. The profiles (and associated specifications) can not use Java SE 9, 10, 11, etc APIs. We are still requiring Java SE 8 APIs.

OK; thanks; I like that framing of it. 

In this context wouldn't the 'profiles' basically mean the implementations of those profiles?

**Comment by bstansberry** [comment]
A general thought: 

*IF* the basic idea is that an EE 9.1 product runs on JDK 11, but must use the JDK 8 class level and must not use any JDK 11 APIs 

*AND IF* it also wants to certify on SE 8, it also certifies as EE 9.0 

*THEN* A general approach to this issue would be to switch any discussion of what API is exposed to the application to JDK 11, and then deal with class level / source level specially.

This could work for 9.1 if the specs basically have no functional changes vs 9.0 wherein a vendor who wanted to couldn't certify the same server against both 9.0 and 9.1.  I believe that is the intent.

For EE 10 it would be good IMHO to have some more flexible language (and TCK) related to all this, to make it easier to certify against > 1 SE version, e.g. 11 and 17.  But I think that should be out of scope for this issue, as we need to get 9.1 done and AIUI the 9.1 TCK won't support two versions anyway.

**Comment by kwsutter** [comment]
> _THEN_ A general approach to this issue would be to switch any discussion of what API is exposed to the application to JDK 11, and then deal with class level / source level specially.

At first, I didn't agree with this position.  But, as I was writing the reply, it was starting to make sense.  So, in EE 9.1, we would surface the JDK 11 API to highlight the fact that some of the APIs were removed from JDK 8.  But, if we still require the JDK 8 source level compatibility, then we won't get into the problems of introducing new JDK 11 APIs into our Jakarta EE APIs.  Not in EE 9.1 anyway...

Is this what you were thinking?

> This could work for 9.1 if the specs basically have no functional changes vs 9.0 wherein a vendor who wanted to couldn't certify the same server against both 9.0 and 9.1. I believe that is the intent.

Yes, this is exactly my intent.  No functional changes between 9.0 and 9.1 -- except for the optional aspects that we've been discussing in regards to the CORBA ORB.

**Comment by bstansberry** [comment]
Yes, that is what I was thinking.

The foundation for this is my (possibly mistaken) impression that the 9.1 TCK is going to only run on JDK 11 and sorting things like getting signature tests to work independent of the underlying JDK is going to come later. So no product will be able to certify 9.1 on SE 8.

**Comment by bstansberry** [comment]
Hmm, I see that https://docs.google.com/document/d/1EJ2ilaPhMnQqa3aw6AmwjRbBPGL3_np4uuwklgfqPZI/edit#heading=h.g0fnoi79i3oj notes that "Jakarta EE 9.1 TCK needs to allow execution with either Java SE 8 or Java SE 11" so my impression is wrong.

**Comment by bstansberry** [comment]
Related to this, and not incorporated in what I've done up to now in #302, is the treatment of the various "enterprise technologies" listed in section 6.1.1. My current PR includes this statement before that list of SE APIs: "If the container provides a version of the Java SE platform newer than Java SE 8 and that version no longer includes one or more APIs that were available in Java SE 8, the container is not required to provide those APIs, unless they are one of the enterprise technologies listed in this specification."

But the discussion David Blevins started at https://www.eclipse.org/lists/ejb-dev/msg00176.html led me to look more closely at the list, and I think we should improve that. A number of the items in the list have a footnote leading to:

"[15] Removed from Java SE 11. See Required Jakarta Technologies."

For those that EE has picked up, that footnote kind of works. (I think per API footnotes that specifically call out the relevant 'Required Jakarta Technology would be better.). But for Java IDL And RMI-IIOP we need a different footnote, one that notes the API is removed from SE 11 but then states the container must provide those APIs if relevant EE technology xxx is provided.  Then for both IDL and RMI-IIOP xxx would include CORBA/IIOP, and then for RMI-IIOP it might include EJB 2.x remote client views, depending on what the decision coming out of the ejb-dev thread I linked is.
