### ISSUE TITLE
Compatibility certification request for Thunisoft Application Server for Full Platform

### ISSUE THREAD

**Issue by zcwslnh** [eclipse-ee4j/jakartaee-platform#290]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>

  [Beijing Thunisoft Information Technology Co.,Ltd](http://www.thunisoft.com)
- [x] Product Name, Version and download URL (if applicable):<br/>

 [Thunisoft Application Server 2.8](http://www.thunisoft.com/tas/index.jhtml)

- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, Full Profile 8](https://jakarta.ee/specifications/platform/8/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform CTS 8.0.2](http://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip),SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
- [x] Public URL of TCK Results Summary:<br/>
  [TCK Results Summary](http://www.thunisoft.com/tastckresults/index.jhtml)
- [x] Any Additional Specification Certification Requirements:<br/>
   [Jakarta Dependency Injection 1.0 TCK](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)
   b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f<br/>
  [Jakarta Contexts and Dependency Injection 2.0 TCK](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)
75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808<br/>
  [Jakarta Bean Validation 2.0 TCK](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip)
b6778914f78bfcce5d6934347d71502603b1b0a6bbfdfbcf956271c367d40974<br/>
- [x] Java runtime used to run the implementation:<br/>
OracleJDK Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS Version: CentOS Linux release 7.5.1804 (Core)
Database Version: 10.14.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM 
+1

**Comment by hantsy** [comment]
@zcwslnh Can you provide a public URL to download and try the application server?

Personally, I can not find a page to describe the technology details of this application server in your website?

**Comment by kwsutter** [comment]
LGTM as well!  Thank you!

**Comment by kwsutter** [comment]
I agree with @hantsy that it would be nice to be able to read something about your application server.  As a workaround, I took a copy of the "product description" page and ran it through Google Translate.  Here's what I got...

Product Description

TAS is called Thunisoft application server, which is an enterprise-level middleware product independently developed by Huayu. It supports servlet3.1 and jsp2.3 specifications and has powerful management functions. The TAS management console can be accessed through a browser. In the console, you can visually publish standard war package applications, configure data sources, modify server configurations, maintain user lists, monitor server running status, and manage clusters.

TAS contains two sub-products, namely TAS server and TAS load balancer. The TAS server is an independent server used to run applications. The TAS load balancer is referred to as TAS LB, which is the control center of the TAS cluster. TAS LB provides a unified access interface to the outside world and forwards requests to the TAS servers in the cluster.

TAS server architecture

The TAS server adopts a component-based architecture system, each function is encapsulated in a software component, and an IOC container in the form of XML is used to assemble various functional components to form a fully functional enterprise-level application server.

TAS cluster architecture

The TAS cluster adopts a bus architecture system, and the TAS cluster console communicates with each TAS server node through a remote bus. The application deployment status can be obtained through the remote bus, and the application mapping table in the load balancer can be updated. The load balancer distributes requests to the TAS server according to the application mapping table.
