### ISSUE TITLE
Compatibility certification request for [product/project name] for [Full Platform|Web Profile]

### ISSUE THREAD

**Issue by andreygordon021** [eclipse-ee4j/jakartaee-platform#292]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  // Add here
- [x] Product Name, Version and download URL (if applicable):<br/>
  // Add here
- [x] Specification Name, Version and download URL:<br/>
   // Add here
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  // Add here
- [x] Public URL of TCK Results Summary:<br/>
  // Add here
- [x] Any Additional Specification Certification Requirements:<br/>
  // Add here
- [x] Java runtime used to run the implementation:<br/>
  // Add here
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  // Add here
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
It looks like this was added unintentionally.
