### ISSUE TITLE
Remove Applet references

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#298]
[Applet spec.](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/applet/Applet.html
) is deprecated in Java SE 9. There is no replacement API. 

Oracle [have announced](https://www.oracle.com/technetwork/java/javase/javaclientroadmapupdatev2020may-6548840.pdf) intention to begin removal of APIs from Java SE beginning in 2020. 

References to Applet should be removed in Platform and other ancillary specifications from a future release.

**Comment by kwsutter** [comment]
Looks like PR #302 may be resolving this Issue as well...

**Comment by kwsutter** [comment]
I just did a further search on "applet" in the Platform spec.  The changes proposed in PR #302 will start this activity, but it won't complete the issue.

**Comment by kwsutter** [comment]
As my previous comment indicated, we have started this removal of the Applet references, but there is much more to do.  Besides textual updates, there are also diagrams that need updating.  I plan to move this out of the "required for 9.1" category unless I hear otherwise.

**Comment by kwsutter** [comment]
Per my earlier comment, I have removed this Issue from the 9.1 Project plan.  There is more work to be done in the Platform Spec to completely remove the Applet references and that's not going to be completely done before 9.1 completes.

**Comment by starksm64** [comment]
Applets still have not been actually removed even though https://openjdk.java.net/jeps/398 says this was done for 17. It looks like was done was to add a forRemoval=true attribute to the deprecated annotation:
@Deprecated(since = "9", forRemoval = true)

We can look at removing this again for EE10.

**Comment by starksm64** [comment]
The applet container has been removed for EE10.
