### ISSUE TITLE
Ensure CORBA is properly specified as being Optional

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#300]
In Jakarta EE 9, the CORBA was declared Optional in the Platform Spec.  We need to ensure that we have a consistent message regarding this Optional aspect of CORBA in the 9.1 release.  This is especially important since the CORBA ORB is no longer part of the Java SE 11 runtime (it was still part of the Java SE 8 runtime).  Thus, with the move to support Java SE 11 in Jakarta EE 9.1, we need to ensure the message is clear.

As one searches for "CORBA" in the Platform spec, most of the references are clearly marked as Optional.  It looks like we're in pretty good shape.  Here's what I found and my initial assessments.  We'll get some eyes on this material and see what type of PR will be required to clean this up (if necessary).

**2.7.4. RMI-IIOP (Optional)**
Good.

**2.7.5. Java IDL (Optional)**
Good.

**2.8. Interoperability**
Good -- just indicates that CORBA is outside of the scope of the Jakarta EE Platform definition.

**5.1.1. Chapter Organization**
Good - just provides a pointer to the ORB References section.

**Section 5.12 ORB References**
Although the very last sentence of this section states the optional support requirement, we should probably highlight that fact earlier in the section:
`The requirements in this section only apply to Jakarta EE products that include support for interoperability using CORBA.`

**6.2.3.5. RMI-IIOP**
I think this section is okay since it continually indicates that an application server or container **may** provide support for CORBA.

**6.2.3.6. JNDI**
Probably okay -- it states that applications *may* lookup a CORBA ORB instance.

**6.3. Enterprise Beans 4.0 Requirements**
Again, probably okay.  This section was revamped for Jakarta EE 9 and there is no commitment for support of CORBA or the ORB.

**7.1. Introduction to Interoperability**
Again, probably okay.  This section mentions that platforms *may* provide CORBA support.

**9.6. Optional Features for Jakarta EE Profiles**
This is good.  Very clearly states that CORBA and the ORB are optional features.

**Appendix D: Related Documents**
Just a reference to some CORBA documentation.

**Comment by kwsutter** [comment]
@dblevins Any input on this  Issue?  The Description highlights all of the areas of the Platform Spec that seems to reference the CORBA Orb capability.  I think we're in pretty good shape here with marking it as optional.  Comments and suggestions from you would be appreciated.  Thanks.

**Comment by kwsutter** [comment]
Child Issue of Epic #312.

**Comment by dblevins** [comment]
Following up our discussion on #323 over here.  I'll build the spec and do a once-through to see how everything looks.  That'll probably be early next week.
