### ISSUE TITLE
Compatibility certification request for Eclipse Jetty for Servlet

### ISSUE THREAD

**Issue by WalkerWatch** [eclipse-ee4j/jakartaee-platform#308]
- [X] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Jetty, https://www.eclipse.org/jetty/
- [X] Product Name, Version and download URL (if applicable):<br/>
  Jetty 11.0.1, https://www.eclipse.org/jetty/download.php
- [X] Specification Name, Version and download URL:<br/>
   Jakarta Servlet 5.0     https://jakarta.ee/specifications/servlet/5.0/
- [X] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
 Servlet TCK 5.0.1  https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/servlet-tck-5.0.1.zip   SHA256SUM: 915e269802a39a71b006d8beb62ebece74a1bb6586d5d2bebf60f7ab4d123a5b
- [X] Public URL of TCK Results Summary:<br/>
  https://jenkins.webtide.net/job/tck/job/servlettck-run-jetty-11.0.x/lastCompletedBuild/TCK_20Report/
- [X] Any Additional Specification Certification Requirements:<br/>
  N/A
- [X] Java runtime used to run the implementation:<br/>
  JDK 11
- [X] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Unbuntu
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
@WalkerWatch This is awesome!!!
Can you file this issue to the Servlet issue tracker, https://github.com/eclipse-ee4j/servlet-api/issues? Or maybe @eclipsewebmaster can transfer it for us?

**Comment by WalkerWatch** [comment]
@ivargrimstad Happy to open one there if @eclipsewebmaster cannot move it. Sorry about that, thought this was the place.

**Comment by TanjaObradovic** [comment]
Very exciting news!

**Comment by WalkerWatch** [comment]
@ivargrimstad Went ahead and just[ opened one there](https://github.com/eclipse-ee4j/servlet-api/issues/394). Will close this issue for now.
