### ISSUE TITLE
About the differences between the "full platform," "full profile," "micro profile," and "web profile" of the Jakarta EE specification

### ISSUE THREAD

**Issue by AndyLuke** [eclipse-ee4j/jakartaee-platform#318]
Hi, When I download OpenLiberty from https://www.openliberty.io/downloads/, I found that there are several versions of OpenLiberty, as there were when I download Wildfly.So I learned that these different versions had something to do with Jakarta EE specifications(such as Jakarta EE full profile, Jakarta EE full platform).But I did't find the difference between these specifications, so could you help me to distinguish the difference between these?

**Comment by ivargrimstad** [comment]
@AndyLuke Here are the links to the specifications for [Jakarta EE Platform](https://jakarta.ee/specifications/platform/) and [Jakarta EE Web Profile](https://jakarta.ee/specifications/webprofile/).

We don't use the terms "full profile" or "full platform", that would be the Jakarta EE Platform.

I don't think this issue belongs here, so I'll close it. If there any issues with the OpenLiberty download page, please file an issue in their issue tracker.
