### ISSUE TITLE
Compatibility certification request for Apusic Application Server for Web Profile

### ISSUE THREAD

**Issue by PatrickHuang888** [eclipse-ee4j/jakartaee-platform#328]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
[Kingdee Apusic Cloud Computing](http://www.apusic.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
AAS V10-EE9
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Web Profile 9.0](https://jakarta.ee/specifications/webprofile/9/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform TCK 9.0.2](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/jakartaeetck-9.0.2.zip) 
 
SHA-256: b7fbb6c74d75621df04beadd0510ebbf5a4ae48c63370fa7358d630c717e688c
- [x] Public URL of TCK Results Summary:<br/>
http://www.apusic.com/aas_v10_ee9_webtck
- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Contexts and Dependency Injection [cdi-tck-3.0.1-dist.zip](https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip)  
SHA-256: f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d

Jakarta Bean Validation [beanvalidation-tck-dist-3.0.0.zip](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip)  
SHA-256: c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b

Dependency Injection [jakarta.inject-tck-2.0.1-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip)  
SHA-256: 7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6

Debugging [jakarta-debugging-tck-2.0.0.zip](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip)  
SHA-256: 71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc
- [x] Java runtime used to run the implementation:<br/>
Oracle JDK 1.8.0_201-b09
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
Apache Derby, Linux, Ubuntu 20.04.2 LTS
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
+1  Thanks, @PatrickHuang888!

**Comment by ivargrimstad** [comment]
+1 LGTM

**Comment by PatrickHuang888** [comment]
Thanks, @kwsutter and @ivargrimstad !
