### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 6.1 RC1, Jakarta EE Platform, 9.1

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-platform#334]
- [x] Organization Name ("Organization") and, if applicable, URL:
   Eclipse Foundation

- [x] Product Name, Version and download URL (if applicable):
   [Eclipse GlassFish 6.1 RC1](https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0-RC1.zip)

- [x] Specification Name, Version and download URL:
  [ Jakarta EE Platform 9.1](https://jakarta.ee/specifications/platform/9.1/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:
 [ Jakarta EE Platform TCK, 9.1](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.1.0.zip), SHA-256: `16904b7ccd7ae61287b763587e8bfbff50608ab09f3876bb41af65d043263ca7`

- [x] Public URL of TCK Results Summary:
  [Eclipse GlassFish 6.1 RC1 TCK Results](https://glassfish.org/certifications/jakarta-platform/9.1/TCK-Results-6.1-RC1)

- [x] Any Additional Specification Certification Requirements:
  [Jakarta Dependency Injection 2.0.1 TCK](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip) - SHA-256: `7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6`
  [Jakarta Contexts and Dependency Injection 3.0.1 TCK](http://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip) - SHA-256: ` f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d`
  [Jakarta Bean Validation 3.0.0 TCK ](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip) - SHA-256: `c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b`
   [Jakarta XML Binding 3.0.1 TCK](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.1.zip) - SHA-256: `a9356a2eb989e8cb7f663ed5fd244d8e2d222e2c4108c40c65001bec90f40baf` 

- [x] Java runtime used to run the implementation:
```
java version "11.0.7" 2020-04-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.7+8-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.7+8-LTS, mixed mode)
```

- [x] Summary of the information for the certification environment, operating system, cloud, ...:
   Apache Derby,
   Linux, CentOS 7

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
The link to the Bean Validation TCK points to version 3.0.0. The SHA-256 matches, so I guess it is just the link text that should be changed from 3.0.1 to 3.0.0?

`$ sha256sum beanvalidation-tck-dist-3.0.0.zip 
c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b  beanvalidation-tck-dist-3.0.0.zip`

Otherwise, everything looks good!

**Comment by edbratt** [comment]
> The link to the Bean Validation TCK points to version 3.0.0. The SHA-256 matches, so I guess it is just the link text that should be changed from 3.0.1 to 3.0.0?

Fixed all four issues. Thanks for spotting that.

**Comment by kwsutter** [comment]
LGTM as well!  +1

**Comment by scottmarlow** [comment]
:+1:
