### ISSUE TITLE
Compatibility certification request for ManageCat ManageFish Server for Jakarta EE (Full) Platform, 9.1 

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/jakartaee-platform#350]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  ManageCat, https://www.managecat.com

- [x] Product Name, Version and download URL (if applicable):<br/>
  [ManageFish, 6.1.0](https://download.managecat.com/6.1.0/managefish-fullprofile-6.1.0.zip),  

- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform 9.1](https://jakarta.ee/specifications/platform/9.1/)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK, 9.1,](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.1.0.zip) SHA-256: 16904b7ccd7ae61287b763587e8bfbff50608ab09f3876bb41af65d043263ca7

- [x] Public URL of TCK Results Summary:<br/>
[ManageFish Test Results](https://managecat.com/tck-test-results)

- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Contexts and Dependency Injection 3.0 TCK

 https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip
 SHA-256: **f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d**

Jakarta Dependency Injection 2.0 TCK
https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip
SHA-256: **7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6**

Jakarta Bean Validation 3.0 TCK
https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip
SHA-256:
**c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b**

Jakarta XML Binding 3.0.1 TCK
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-binding-tck-3.0.1.zip
SHA-256:
**a9356a2eb989e8cb7f663ed5fd244d8e2d222e2c4108c40c65001bec90f40baf**

- [x] Java runtime used to run the implementation:<br/>
  LibericaJDK build of OpenJDK
  openjdk version "11.0.11" 2021-04-20 LTS
  OpenJDK Runtime Environment (build 11.0.11+9-LTS)
  OpenJDK 64-Bit Server VM (build 11.0.11+9-LTS, mixed mode)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby
  Linux, Ubuntu 20.04.1 LTS

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
Wow!  Exciting news, @gerdogdu!  Just a couple of comments...

- First off, these are my personal observations.  These may need to be further vetted by the Specification Committee...
- It definitely looks like ManageFish satisfies the requirements for a Jakarta EE Compatible Implementation.  Congratulations!
- Your website indicates this is a commercially supported version of Eclipse Glassfish.  Since Eclipse Glassfish is already listed on the ballot as an open-source CI used for ratification, there is no requirement to list additional derivatives of Glassfish on the ballot (https://github.com/jakartaee/specifications/pull/372).
- But, I would definitely follow through on the process to get your project listed on the Compatible Products page (https://jakarta.ee/compatibility/).

Thanks again!

**Comment by gerdogdu** [comment]
Thanks Kevin.

> Your website indicates this is a commercially supported version of Eclipse Glassfish. Since Eclipse Glassfish is already listed on the ballot as an open-source CI used for ratification, there is no requirement to list additional derivatives of Glassfish on the ballot (jakartaee/specifications#372).

Yes, but this is our own distribution (own TCK process). Is there anything which prohibits to put it into the ballot? Our efforts deserve to be in ballot.

If no problem for the committe, we would like to be in ballot.

**Comment by kwsutter** [comment]
> If no problem for the committee, we would like to be in ballot.
> Warm regards.

Thanks for the quick reply, @gerdogdu.  I have sent a note to the Spec Committee to get their reading on this unique request.  Since we're trying to get the ballot out today, I am really hoping for a quick turnaround.  :-) Thanks for your patience!

**Comment by gerdogdu** [comment]
Thanks Kevin. I need to have some sleep now :)

**Comment by ivargrimstad** [comment]
CCR Looks good

**Comment by starksm64** [comment]
There is no question this is a valid CCR for a compatible implementation request. What has certainly caught us off guard is this issue of what CCRs should be called out on the ballot for the associated specification. I do believe there should be some significant difference in the implementations associated with the CCR, but we have not established that criteria in the steering or specification committees.

**Comment by jeanouii** [comment]
@gerdogdu can you double check the result page please.
This does not look quite right

`Jakarta Debugging Support for Other Languages 2.0 TCK
http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/debugging-tck-2.0.0.zip
SHA-256:
230ee696e714b3fd0f832e12f7c919737cd088f0b004717f601e40c4958260aa`

**Comment by gerdogdu** [comment]
> This does not look quite right
> 
> `Jakarta Debugging Support for Other Languages 2.0 TCK http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/debugging-tck-2.0.0.zip SHA-256: 230ee696e714b3fd0f832e12f7c919737cd088f0b004717f601e40c4958260aa`

What is the problem?

**Comment by jeanouii** [comment]
The link is wrong and the hash does not match

**Comment by gerdogdu** [comment]
> The link is wrong and the hash does not match

Thanks. We have updated.

**Comment by ivargrimstad** [comment]
After a release ballot, the zip file containing the TCK is copied from the `promoted` location under `ee4j` to the graduated location under `jakartaee`. In this case it seems like the promoted file has been updated after the graduation somehow.

The correct location is:
https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip 

For future reference: Always get the TCKs from the 'jakartaee' download location to be sure that it is the correct version. The promoted area is fine to use up until graduation of the spec.

**Comment by gerdogdu** [comment]
>  I do believe there should be some significant difference in the implementations associated with the CCR, but we have not established that criteria in the steering or specification committees.

I am not agree with this. If you look at OpenJDK, there are lots of certified, JCK compatible distribution of them even some  of the vendors not contributing back to OpenJDK upstream. We contribute to GF upstream project and having our own build and TCK process different than GF.

In the meantime, this is our first release, and in the coming releases, there will more add-on features (like a  different admin console, replacing Weld with the our own DI implementation etc.)

Frankly, this is up to you whether put into the ballot or not. But, we have done fair amount of work on this.

**Comment by starksm64** [comment]
> > I do believe there should be some significant difference in the implementations associated with the CCR, but we have not established that criteria in the steering or specification committees.
> 
> I am not agree with this. If you look at OpenJDK, there are lots of certified, JCK compatible distribution of them even some of the vendors not contributing back to OpenJDK upstream. We contribute to GF upstream project and having our own build and TCK process different than GF.
> 
> In the meantime, this is our first release, and in the coming releases, there will more add-on features (like a different admin console, replacing Weld with the our own DI implementation etc.)
> 
> Frankly, this is up to you whether put into the ballot or not. But, we have done fair amount of work on this.

You are missing the distinction between being a compatible implementation that is listed on the ballot for the final platform specification ratification and being a compatible implementation in general, which is all the JCK has.
As I said, there is no problem with ManageFish being listed as a compatible implementation. The debate is whether ManageFish should be listed as a compatible implementation used to validate the platform specification.

**Comment by gerdogdu** [comment]
> As I said, there is no problem with ManageFish being listed as a compatible implementation. The debate is whether ManageFish should be listed as a compatible implementation used to validate the platform specification.

If it is being as a compatible implementation, then it is absolutely used for validating the platform specification. It has no difference than others.

**Comment by starksm64** [comment]
That would be true if GlassFish was not already listed. ManageFish is not an independent implementation, it is a derivative of GlassFish that is an independent build and run of the TCK. We have a long standing issue to remove GlassFish as the goto implementation for verifying specifications. If ManagedCat had said that it would provide the CCR that demonstrates a derivative of GlassFish can pass the 9.1 platform specification, and this allowed avoided having to create a GlassFish CCR, then I would agree that ManagedFish should be listed as an implementation for ratification. We'll have to debate this further on the May 5 specification committee call.

**Comment by gerdogdu** [comment]
From my open source perspective, every vendor can definitely create a derivative of any other open source products and this derivative can also be used for the ballot (before the deadline). ManageFish and GlassFish are two different products from different organizations/vendors which only shares the same codebase. If I create a derivative of Wildfly, pass the TCK and prepare CCR, then it can also be used for ballot.

In the mean time, I don't see any difference between the compatible implementation and platform specification ratification (Other than deadline issue). It is an egg-chicken problem. ManageFish can also be used for platform specification ratification. What is the problem (or effect) of adding two similar products into the ballot? I think this shows the strength of the platform adaptation. 

For example, our product builds with Liberica JDK on Ubuntu specific version. This may not be compatible with GlassFish.
Anyway, I think it is enough from my side :)

**Comment by starksm64** [comment]
Right, and if you beat Red Hat to the punch to provide a CCR for a specification that uses a compatible implementation that is a derivative of Wildfly, then that should be considered a ratifying candidate. The criteria I'll argue as sufficient for consideration as a ratifying candidate in the specification committee call is that the implementation brings a high probability of new patentable implementation details to the vote. Are there source code changes to the codebase to support running with Liberica JDK on Ubuntu?

This has nothing to do with open source and the ability to create derivative works. It has to do with what strengthens the specification in terms of the breadth of essential patent grants. Others may argue that any implementation, derivative or otherwise is beneficial in terms of ratifying the spec. It is up to the specification committee to determine how to handle this.

Regardless, ManageFish is a new supported compatible implementation, and we can make sure to have every compatible implementation available at the time of the 9.1 announcement listed.

**Comment by gerdogdu** [comment]
> Are there source code changes to the codebase to support running with Liberica JDK on Ubuntu?
Not at the moment but it will be but our aim is to provide most of our extensions to upstream project. My point is that  they are two different products even if 100% code compatibility. 

In the mean time, thanks for your valuable comments.

**Comment by kwsutter** [comment]
@gerdogdu Lively conversation while I was out yesterday afternoon...  :-)  As @starksm64 mentioned, this will be discussed in the Spec Committee call tomorrow.  But, since we have no precedent at this moment, I am making the update in the PR to include ManageFish for the ballot.  If something changes due to the Spec Committee call, I will adjust.  Thanks for your patience while we work through this.
