### ISSUE TITLE
Define Jakarta EE Web Profile 10

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#363]
We need to define the content of Jakarta EE Web Profile 10. 

The current required specifications (for 9.1) are grouped by planned updates below as an input to the discussion:

### Major updates
- Jakarta Servlet 5.0 -> 6.0
- Jakarta Expression Language 4.0 -> 5.0
- Jakarta Standard Tag Library 2.0 -> 3.0
- Jakarta Faces 3.0 -> 4.0
- Jakarta RESTful Web Services 3.0 -> 3.1 or 4.0
- Jakarta Security 2.0 -> 3.0
- Jakarta Authentication 2.0 -> 3.0
- Jakarta Contexts and Dependency Injection 3.0 -> 4.0

### Minor updates
- Jakarta Server Pages 3.0 -> 3.1
- Jakarta WebSocket 2.0 -> 2.1
- Jakarta JSON Processing 2.0 -> 2.1
- Jakarta JSON Binding 2.0 -> 2.1
- Jakarta Persistence 3.0 -> 3.1

### No updates
- Jakarta Debugging Support for Other Languages 2.0
- Jakarta Annotations 2.0
- Jakarta Enterprise Beans 4.0 Lite
- Jakarta Transactions 2.0
- Jakarta Bean Validation 3.0
- Jakarta Managed Beans 2.0
- Jakarta Interceptors 2.0
- Jakarta Dependency Injection 2.0

### Proposed new additions
- Jakarta MVC 2.1 - https://github.com/eclipse-ee4j/jakartaee-platform/issues/381
- _Jakarta Config 1.0 (no plan proposed yet)_
- Jakarta Concurrency 3.0

**Comment by smillidge** [comment]
I would like to suggest adding Jakarta Concurrency 3.0

**Comment by kwsutter** [comment]
> I would like to suggest adding Jakarta Concurrency 3.0

Just like @ivargrimstad did for MVC, it might be good to create a new Issue for including Concurrency in Web Profile.  And, then gather, collect, and publish some data in support of this move.  Thanks!

**Comment by kwsutter** [comment]
>     * Jakarta Config 1.0 (no plan proposed yet)

If the Core Profile becomes real in Jakarta EE 10, and Core Profile consumes Config 1.0, then we should change the content of Web Profile to include the Core Profile and adjust the overall list accordingly.

**Comment by kwsutter** [comment]
Linking the API packaging Issue here in the Web Profile as well...  https://github.com/eclipse-ee4j/jakartaee-api/issues/107

**Comment by kwsutter** [comment]
> > ```
> > * Jakarta Config 1.0 (no plan proposed yet)
> > ```
> 
> If the Core Profile becomes real in Jakarta EE 10, and Core Profile consumes Config 1.0, then we should change the content of Web Profile to include the Core Profile and adjust the overall list accordingly.

If the goal is to keep these Profiles independent, then making Web Profile dependent on Core Profile may not be the best process.  We may end up just making Config 1.0 a member of both Web Profile and Core Profile.

**Comment by ivargrimstad** [comment]
As far as I can see, the current platform spec does not state that the platform depends on the Web Profile but lists all the specs that are included. I think we should continue that approach with new profiles. The profile section (section 9) opens up for profiles to be intersections or direct subsets of other profiles. 

So I think Config 1.0 (if included) should be explicitly listed as a required spec of Core- and Web Profile as well as in the Platform spec.

**Comment by kwsutter** [comment]
> I would like to suggest adding Jakarta Concurrency 3.0

Based on the discussion on the [mailing list ](https://www.eclipse.org/lists/jakartaee-platform-dev/msg02728.html) and the [Platform Call on 08/03/2021](https://docs.google.com/document/d/1EJ2ilaPhMnQqa3aw6AmwjRbBPGL3_np4uuwklgfqPZI/edit#), we will move forward with including Concurrency in the Web Profile for Jakarta EE 10.

**Comment by smillidge** [comment]
PR made to add Jakarta Concurrency to Web Profile as agreed https://github.com/eclipse-ee4j/jakartaee-api/pull/115

**Comment by lukasj** [comment]
Jakarta JSON Binding goes with 3.0 (instead of 2.1)
