### ISSUE TITLE
Define Jakarta EE Platform 10

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#364]
We need to define the content of Jakarta EE Web Profile 10.
The current required specifications (for 9.1) in addition to those defined by Web Profile (#363) are grouped by planned updates below as an input to the discussion:

### Major updates
- Authorization 2.0 -> 3.0
- Concurrency 2.0 -> 3.0

### Minor updates
- Activation 2.0 -> 2.1
- Batch 2.0 -> 2.1
- Connectors 2.0 -> 2.1
- Mail 2.0 -> 2.1
- Messaging 3.0 -> 3.1

### No updates
- Enterprise Beans 4.0

### Currently optional specs with planned major updates
- XML Binding 3.0 -> 4.0
- XML Web Services 3.0 -> 4.0
- SOAP with Attachments 2.0 -> 3.0

### Currently optional specs with no planned updates
- Enterprise Web Services 2.0
- Web Services Metadata 3.0

**Comment by keilw** [comment]
Are new specs under "Major Upgrades" or somewhere else?
Where is Config in 10?

**Comment by ivargrimstad** [comment]
> Are new specs under "Major Upgrades" or somewhere else?
> Where is Config in 10?

I didn't want to duplicate everything, so it is referenced in the issue for Web Profile (#363).

**Comment by keilw** [comment]
Ok that definitely gets the Web Profile even bigger (in 10) and although some of the optional specs (that are more to remove them from the platform at least) ease that a bit, thinkning about a different kind of optionality as discussed in the last call and once or twice earlier could be a good idea.

**Comment by kwsutter** [comment]
Based on the discussion of today's Platform call, we need to determine whether the handful of unmodified component specs still need a service or minor update due to the Java 11 (or 17) update:
https://docs.google.com/document/d/1EJ2ilaPhMnQqa3aw6AmwjRbBPGL3_np4uuwklgfqPZI/edit?disco=AAAAMkasPQM

**Comment by lukasj** [comment]
Web Services Metadata is no longer available as a separate spec/jar - it is part of the XML Web Services 4.0+

**Comment by hantsy** [comment]
Security 3.0 is not included in JakartaEE 10?

I have added the `jakarta.platform:jakarta.jakartaee-api:10.0.0`, but there is no `OpenIdAuthenticationMechanismDefinition` which is defined in Security 3.0 spec.
