### ISSUE TITLE
Compatibility certification request for BES Application Server v10.0.0 for  Full Platform

### ISSUE THREAD

**Issue by guojjanjun** [eclipse-ee4j/jakartaee-platform#372]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
   https://www.bessystem.com/
- [x] Product Name, Version and download URL (if applicable):<br/>
   BES Application Server v10.0.0
- [x] Specification Name, Version and download URL:<br/>
   <a href="https://jakarta.ee/specifications/platform/9">Jakarta EE Platform 9</a>
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  <a href="https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.0.zip">Jakarta EE						Platform TCK 9.0.0</a>, SHA-256:										<code>75b2493a117e7f8fe775cc7e2e8a605a203611895091f4bb9aaabed57f813392</code>
- [x] Public URL of TCK Results Summary:<br/>
  https://www.bessystem.com/certifications/jakartaee/platform9/10.0.0-TCKResults.html
- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Contexts and Dependency Injection <a href="https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip">cdi-tck-3.0.1-dist.zip</a>,
SHA-256:	<code>f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d</code><br/>
Jakarta Bean Validation <a href="https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip">beanvalidation-tck-dist-3.0.0.zip</a>,	
SHA-256:<code>c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b</code><br/>
Dependency Injection <a href="https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip">jakarta.inject-tck-2.0.1-bin.zip</a>,
SHA-256:<code>7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6</code><br/>
Debugging <a href="https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip">jakarta-debugging-tck-2.0.0.zip</a>,
SHA-256:<code>71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc</code><br/>
- [x] Java runtime used to run the implementation:<br/>
 Oracle JDK 1.8.0_231-b11
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby, Linux, Redhat7.1
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1 LGTM
