### ISSUE TITLE
Compatibility certification request for Payara Server Community 6.2021.1.Alpha1 for Full Platform

### ISSUE THREAD

**Issue by jGauravGupta** [eclipse-ee4j/jakartaee-platform#375]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
[Payara Services Ltd](https://www.payara.fish/)

- [x] Product Name, Version and download URL (if applicable):<br/>
[Payara Server Community 6.2021.1.Alpha1](https://repo1.maven.org/maven2/fish/payara/distributions/payara/6.2021.1.Alpha1/payara-6.2021.1.Alpha1.zip)
  
- [x] Specification Name, Version and download URL:<br/>
[Jakarta EE Platform, Full Profile 9.1](https://jakarta.ee/specifications/platform/9.1)
   
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform CTS 9.1](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.1.0.zip), SHA-256: 16904b7ccd7ae61287b763587e8bfbff50608ab09f3876bb41af65d043263ca7

- [x] Public URL of TCK Results Summary:<br/>
[https://docs.payara.fish/community/docs/jakartaee-certification/6.2021.1.Alpha1/tck-results-full-6.2021.1.Alpha1.html](https://docs.payara.fish/community/docs/jakartaee-certification/6.2021.1.Alpha1/tck-results-full-6.2021.1.Alpha1.html)

- [x] Any Additional Specification Certification Requirements:<br/>

- Jakarta Dependency Injection 2.0 TCK
Download URL & SHA-256:
[jakarta.inject-tck-2.0.1-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip)
7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6

- Jakarta Contexts and Dependency Injection 3.0 TCK
Download URL & SHA-256:
[cdi-tck-3.0.1-dist.zip](https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip)
f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d

- Jakarta Bean Validation 3.0 TCK
Download URL & SHA-256:
[beanvalidation-tck-dist-3.0.0.zip](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip)
c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b

- [x] Java runtime used to run the implementation:<br/>
 Zulu JDK Runtime Environment (zulu-11-amd64)

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
 Linux Ubuntu 18.04 LTS

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
The SHA-256 for the 9.1 CTS in the issue does not match the one used in the TCK results. 
The correct value should be: `16904b7ccd7ae61287b763587e8bfbff50608ab09f3876bb41af65d043263ca7`

**Comment by ivargrimstad** [comment]
+1 LGTM

**Comment by kwsutter** [comment]
I know @ivargrimstad already `accepted` it, but +1 from me as well.  Thanks!
