### ISSUE TITLE
Compatibility certification request for Apusic AAS for Jakarta EE 9.1 Full Platform

### ISSUE THREAD

**Issue by PatrickHuang888** [eclipse-ee4j/jakartaee-platform#382]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Kingdee Apusic Cloud Computing](http://www.apusic.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  AAS V10-EE9
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform 9.1](https://jakarta.ee/specifications/platform/9.1/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK, 9.1](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/promoted/jakartaeetck-9.1.0.zip)
SHA256SUM: 2157f31cfc49b8e6c3747270b4cc2a71fd63e79e8066c26a645db8d36305bf6a
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](http://www.apusic.com/aas_v10_ee9-1_full)
- [x] Any Additional Specification Certification Requirements:<br/>
  Jakarta Contexts and Dependency Injection [cdi-tck-3.0.1-dist.zip](https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip), SHA-256: f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d

Jakarta Bean Validation [beanvalidation-tck-dist-3.0.0.zip](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip), SHA-256: c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b

Dependency Injection [jakarta.inject-tck-2.0.1-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip), SHA-256: 7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6

Debugging [jakarta-debugging-tck-2.0.0.zip](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip), SHA-256: 71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc
- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_201-b09
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby, Linux, Ubuntu 20.04.2 LTS
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kwsutter** [comment]
The TCK Results seem to have one error being reported...

ejb30/lite/singleton

   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] Completed running 230 tests.
   [runcts] OUT => [javatest.batch] Number of Tests Passed      = 219
   [runcts] OUT => [javatest.batch] Number of Tests Failed      = 10
   [runcts] OUT => [javatest.batch] **Number of Tests with Errors = 1**
   [runcts] OUT => [javatest.batch] ********************************************************************************

**Comment by PatrickHuang888** [comment]
Hi, kwsutter
as I understand, after first running test harness run failed and errors test again, and after following running log show like this
```console
   [runcts] OUT => [javatest.batch] ********************************************************************************
   [runcts] OUT => [javatest.batch] Completed running 11 tests.
   [runcts] OUT => [javatest.batch] Number of Tests Passed      = 11
   [runcts] OUT => [javatest.batch] Number of Tests Failed      = 0
   [runcts] OUT => [javatest.batch] Number of Tests with Errors = 0
   [runcts] OUT => [javatest.batch] ********************************************************************************
```
and I checked ejb30/lite/singleton test report 
It shows like this:

Tests that passed | 230 | plain view | grouped view
-- | -- | -- | --

**Comment by kwsutter** [comment]
> Hi, kwsutter
> as I understand, after running test harness would run failed and errors test automatically again, and after following running log show like this
> 
> ```
>    [runcts] OUT => [javatest.batch] ********************************************************************************
>    [runcts] OUT => [javatest.batch] Completed running 11 tests.
>    [runcts] OUT => [javatest.batch] Number of Tests Passed      = 11
>    [runcts] OUT => [javatest.batch] Number of Tests Failed      = 0
>    [runcts] OUT => [javatest.batch] Number of Tests with Errors = 0
>    [runcts] OUT => [javatest.batch] ********************************************************************************
> ```
> 
> and I checked ejb30/lite/singleton test report
> It shows like this:
> Tests that passed 	230 	plain view 	grouped view

Okay.  Now I see the re-execution of the tests.  I see that you have to do this re-execution on three separate buckets to get zero errors:
- ejb30/lite/packaging
- ejb30/lite/singleton
- ejb30/lite/tx

You are correct that the re-execution of tests are considered okay.  Personally, I would dive a bit deeper into these failures to understand why the bucket needs to be re-run to get them successful.  Could be something in your product, or it could be something in the test buckets themselves.  Whatever the reason, it would be good to understand.  Thanks.

**Comment by scottmarlow** [comment]
@PatrickHuang888, if you do determine the cause of test failure and find that the test needs to be improved, please consider creating a pull request with improvements via github.com/eclipse-ee4j/jakartaee-tck.  Help with making test improvements is greatly appreciated!  

Anyone working on improving the TCK tests might want to join the https://accounts.eclipse.org/mailing-list/jakartaee-tck-dev mailing list so that you have a place to ask questions.

**Comment by PatrickHuang888** [comment]
@kwsutter @scottmarlow
I will look into this, thanks for the advice.

**Comment by kwsutter** [comment]
I'm ready to accept this CCR.  +1  Thanks for answering all of the questions, @PatrickHuang888!

**Comment by PatrickHuang888** [comment]
thanks @kwsutter 
I found one error case caused by HeapSize not enough, and OOM when running, can be fixed by setting -Xmx.

**Comment by kwsutter** [comment]
> thanks @kwsutter
> I found one error case caused by HeapSize not enough, and OOM when running, can be fixed by setting -Xmx.

Sounds good!  Although the process allows for the test buckets to be immediately re-run to show success, it's a solid practice to figure out why that second run was required.  The goal should be to execute the buckets just once to show success.  Thanks!
