### ISSUE TITLE
Define Jakarta EE Core Profile 10

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#387]
We need to define the content of Jakarta EE Core Profile 10. 

The current required specifications are grouped by planned updates below as an input to the discussion:

### Major updates
- Jakarta RESTful Web Services 3.0 -> 3.1 or 4.0 depending on  the release timeframe

### Minor updates
- Jakarta Annotations 2.0 -> 2.1
- Jakarta JSON Processing 2.0 -> 2.1
- Jakarta JSON Binding 2.0 -> 2.1

### No updates
- Jakarta Interceptors 2.0
- Jakarta Dependency Injection 2.0

### Proposed new additions
- Jakarta Contexts and Dependency Injection 4.0 Lite
- _Jakarta Config 1.0 (no plan proposed yet)_ depending on suitable release timeframe

**Comment by chakib-mohamed** [comment]
Why adding jaxrs to the core profile ? it could be more minimalistic so users can choose to add jaxrs, jakarta messaging,  mp reactive messaging or any communication library on top of it.
Also, in a serverless environement , it could be bridged with any vendor sdk without the need to jaxrs.

**Comment by starksm64** [comment]
Managed Beans adds nothing and frankly should be dropped. @ManagedBean has no usage in the CDI TCK, while the DI annotations are used extensively. The only reference to @ManagedBean in the CDI spec is in the CDI in Jakarta EE which relates to Web Profile and full Platform integration. It certainly is not part of the Lite part of the specification, so it should not be in the Core Profile.

**Comment by arjantijms** [comment]
@starksm64 you mean pruning Managed Beans from the entire platform and perhaps even from the repos and specifications page and everything? It might clear up things indeed.

**Comment by starksm64** [comment]
Yes, Managed Beans should be removed from Jakarta. It servers to purpose.
