### ISSUE TITLE
Compatibility certification request for InforSuite Application Server V11 for Full Platform

### ISSUE THREAD

**Issue by codff** [eclipse-ee4j/jakartaee-platform#398]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Shandong Cvicse Middleware Co.,Ltd.](http://www.inforbus.com/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [InforSuite Application Server V11](http://www.inforbus.com/as.html)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Full Platform 9.0](https://jakarta.ee/specifications/platform/9/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
[Jakarta EE Platform TCK 9.0.2](https://download.eclipse.org/jakartaee/platform/9/jakarta-jakartaeetck-9.0.2.zip)
`SHA-256:
ffd78f41592f69c846f52f80df3641191a984fd15740be56e83c0a73e9e546b8`
- [x] Public URL of TCK Results Summary:<br/>
[TCK Results Summary](http://www.inforbus.com/InforsuiteAS/platform-tckresults/FullPlatform9.0/)
- [x] Any Additional Specification Certification Requirements:<br/>
Jakarta Injection
[jakarta.inject-tck-2.0.1-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.1-bin.zip)
`SHA-256:
7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6`
Jakarta Contexts and Dependency Injection
[cdi-tck-3.0.1-dist.zip](https://download.eclipse.org/jakartaee/cdi/3.0/cdi-tck-3.0.1-dist.zip)
`SHA-256:
f0a3bdd81ea552ddf2c2a6cd2576f0d5ca45026665cb4a5c42606a58bf1c133d`
 Jakarta Bean Validation
[beanvalidation-tck-dist-3.0.0.zip](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.0.zip)
`SHA-256:
c975fd229df0c40947a9f0a69b779ec92bebb3d21e05fdc65fccc1d11ef5525b`
Jakarta Debugging Support for Other Languages
[ jakarta-debugging-tck-2.0.0.zip](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip)
`SHA-256: 71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc`
- [x] Java runtime used to run the implementation:<br/>
Oracle JDK 1.8.0_301
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
OS Version:CentOS Linux release 7.5.1804 (Core)
Database Version:Apache Derby 10.14.2.0
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
The TCK Result [link](https://www.inforbus.com/InforsuiteAS/platform-tckresults/FullPlatform9.0/) is not working for me. 
Please check if there are any issues with a proxy or any missing configuration.

Everything else looks good!

**Comment by codff** [comment]
> The TCK Result [link](https://www.inforbus.com/InforsuiteAS/platform-tckresults/FullPlatform9.0/) is not working for me.
> Please check if there are any issues with a proxy or any missing configuration.
> 
> Everything else looks good!

@ivargrimstad 
Hello, I have modified the  TCK Result link, please check it again,thank you!

**Comment by ivargrimstad** [comment]
LGTM
