### ISSUE TITLE
Exclude SecurityManager API tests in EE 9 TCK

### ISSUE THREAD

**Issue by mnriem** [eclipse-ee4j/jakartaee-platform#408]
As the SecurityManager API in Java SE has been deprecated and is slated for removal any TCK tests covering this area should be excluded from the TCK and a vendor should be allowed to drop the functionality in their implementations.

**Comment by mnriem** [comment]
Related to #406

**Comment by scottmarlow** [comment]
I am :-1: on removing TCK tests that depend on the Java SE Security Manager in Jakarta EE 9 TCKs.

**Comment by mnriem** [comment]
This should be done for the next revision of EE 9. We already have a 9.1. Why can't this be done for a 9.2 so vendors can run the TCK using newer versions of Java without any issues?

**Comment by keilw** [comment]
I also think it's premature, even with a range of JDKs the Java version that ultimately drops it won't exist before 2-4 years from now and by then even Jakarta EE 11 is expected to be available, so removing it from 10.x maybe, 11 or higher sure, but don't bother fumbling with EE 9. You can use and run Java SE 8 until 2030, same for 11 or 17 where nothing is removed with even more years of extended support, so people who need to run JEE 9 TCKs have to use a JDK version that still has the Security Manager.

**Comment by scottmarlow** [comment]
Since we have already released EE 8 + EE 9, we cannot update the EE 8 or EE 9 TCK, because in my opinion, doing so would invalidate the EE 8/9 releases.

I suggest that this issue be **closed** since there is no action that we can possibly take for the reported issue, other than closing this issue (for the reason I just stated).
