### ISSUE TITLE
Track XML Schemas for Jakarta EE 10

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#411]
Schemas are published at  [jakarta.ee/xml/ns/jakartaee/#10](https://jakarta.ee/xml/ns/jakartaee/#10).

The sources are in the [jakartaee-schemas repository](https://github.com/eclipse-ee4j/jakartaee-schemas).

* Update file name to correct version
* Make sure that includes have the correct version

- [x] jakartaee_9.xsd -> jakartaee_10.xsd
- [ ] jakartaee_web_services_metadata_handler_3_0.xsd
- [ ] batchXML_2_0.xsd
- [x] beans_3_0.xsd -> beans_4_0.xsd
- [ ] jobXML_2_0.xsd
- [x] jsp_3_0.xsd -> jsp_3_1.xsd
- [x] application_9.xsd -> application_10.xsd
- [x] application-client_9.xsd -> application-client_10.xsd
- [ ] connector_2_0.xsd
- [x] ejb-jar_4_0.xsd
- [ ] jakartaee_web_services_2_0.xsd
- [ ] jakartaee_web_services_client_2_0.xsd
- [x] permissions_9.xsd -> permissions_10.xsd
- [x] web-app_5_0.xsd -> web-app_6_0.xsd
- [x] web-fragment_5_0.xsd -> web-fragment_6_0.xsd
- [x] web-common_5_0.xsd -> web-common_6_0.xsd
- [x] web-facesconfig_3_0.xsd -> web-facesconfig_4_0.xsd 
- [x] web-facelettaglibrary_3_0.xsd -> web-facelettaglibrary_4_0.xsd
- [x] web-partialresponse_3_0.xsd -> web-partialresponse_4_0.xsd
- [x] web-jsptaglibrary_3_0.xsd -> web-jsptaglibrary_3_1.xsd

**Comment by scottmarlow** [comment]
Are all of the various SPEC APIs mentioned above producing a new schema update?

**Comment by ivargrimstad** [comment]
> Are all of the various SPEC APIs mentioned above producing a new schema update?

No, not all of them. I created the complete list when I was looking at it last year. The one's that are not being updated should just be ticked off in the list without the "-> new version".

**Comment by starksm64** [comment]
This should be complete via https://github.com/jakartaee/jakarta.ee/pull/1472

**Comment by hantsy** [comment]
There is a no persistence.xml 3.1 and orm 3.1?

**Comment by scottmarlow** [comment]
I thought we had a `persistence_3_1.xsd` before as well.  

@lukasj  Did we remove persistence.xml 3.1?

Fyi @hantsy https://jakarta.ee/xml/ns/persistence/orm/orm_3_1.xsd is shown on https://jakarta.ee/xml/ns/persistence/

**Comment by scottmarlow** [comment]
The git history for https://github.com/jakartaee/jakarta.ee/blob/src/data/persistence_schemas.yml doesn't show a 3.1 persistence.xml

**Comment by lukasj** [comment]
> @lukasj Did we remove persistence.xml 3.1?

What has not been added could not have been removed. Considering the creation of 3.1 version of the schema would be about the version number change and nothing else, I saw no point in providing it especially within the context of the minor release. OTOH orm schema has been updated to 3.1 since there actually is a change.

**Comment by hantsy** [comment]
JPA 3.1 spec with 3.0 persistence.xml and 3.1 orm.xml is a little confused for me. I found Hibernate 6.1.x includes a persistence-3.1.xml in its dist.

**Comment by ivargrimstad** [comment]
I tend to agree with @hantsy here. The schema version (and file name) should follow the spec version even if the only change is the version number.

**Comment by lukasj** [comment]
I agree that being consistent is a good thing and - in general - I'm all for it. Yet there is one more thing to consider - overall impact on the CIs/vendors, docs, TCKs, users as well as the spec itself and - almost invisible - price paid for it (in terms of the work required and maintenance cost) - there always has to be a human being doing and  adopting such change through the chain (a feature request for github copilot or similar tool?). 

Do not take me wrong - it absolutely makes sense to pay such price for major versions and I believe everyone is fine with that. I only think that for minor versions, the price paid is just too high and the effort should be put more on evolution/innovation and less on increasing the complexity of maintenance instead especially when it brings value close to zero.

**Comment by ivargrimstad** [comment]
Fair point. I'll add it to the Platform call agenda for next week. Maybe we can get a policy decision for how to handle this in this case and future releases.
