### ISSUE TITLE
Track jars needing module-info.class

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#421]
We need to track the api jars that have no release plan, but need to be upgraded to support a proper module-info.class. From the https://github.com/eclipse-ee4j/jakartaee-api.git I generated the following list of api jars that don't have module-info.class entries.

[jakarta.websocket-api-2.0.0.jar, jakarta.el-api-4.0.0.jar, jakarta.servlet.jsp-api-3.0.0.jar, jakarta.inject-api-2.0.0.jar, jakarta.enterprise.cdi-api-3.0.0.jar, jakarta.jakartaee-web-api-10-SNAPSHOT.jar, jakarta.enterprise.concurrent-api-2.0.0.jar, jakarta.faces-3.0.0.jar, jakarta.faces-api-3.0.0.jar, jakarta.ejb-api-4.0.0.jar, jakarta.batch-api-2.0.0.jar, jakarta.authorization-api-2.0.0.jar, jakarta.transaction-api-2.0.0.jar, jakarta.servlet.jsp.jstl-api-2.0.0.jar, jakarta.validation-api-3.0.0.jar, jakarta.interceptor-api-2.0.0.jar, jakarta.servlet-api-5.0.0.jar, jakarta.jms-api-3.0.0.jar, jakarta.authentication-api-2.0.0.jar, jakarta.security.enterprise-api-2.0.0.jar, jakarta.resource-api-2.0.0.jar]

The api jars without a release plan trims this down to:
[jakarta.inject-api-2.0.0.jar, jakarta.ejb-api-4.0.0.jar, jakarta.transaction-api-2.0.0.jar, jakarta.validation-api-3.0.0.jar, jakarta.interceptor-api-2.0.0.jar]

I'll create project issues for service releases of the API jars for these to track their progress.

**Comment by kwsutter** [comment]
> There is a current platform dev thread related to the topic that you can send your feedback to.

https://www.eclipse.org/lists/jakartaee-platform-dev/msg02813.html

**Comment by starksm64** [comment]
All jars have been updated and released.

**Comment by Sineaggi** [comment]
Unless I'm mistaken it doesn't seem like the faces-api jar is modular?
