### ISSUE TITLE
Required Jakarta Technologies refers to SE 8, should be SE 11

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#434]
The last part of the "Required Jakarta Technologies" section of the Platform spec has this statement:

"If a container supports a newer version of the Java SE platform than Java SE 8, all classes and interfaces provided by the container to satisfy the platform requirements listed above must be compiled with the Java SE 8 source and class level."

This is out of date with our Java SE 11 baseline requirement and needs to be updated to replace SE 8 with SE 11.

**Comment by ederks85** [comment]
PR provided in 455
