### ISSUE TITLE
Need to find a place to host xsds

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse-ee4j/jakartaee-platform#45]
For the schemas for Jakarta EE, where should these be hosted?
e.g. for the following one:
http://xmlns.jcp.org/xml/ns/javaee/application_8.xsd

**Comment by ggam** [comment]
I think the Jakarta EE website would be the ideal place.

Something like: http://jakarta.ee/xml/ns/application_8.xsd

**Comment by bshannon** [comment]
The schema locations should not change for Jakarta EE 8.  Jakarta EE 8 needs to be compatible
with Java EE 8, which defines those locations.

Jakarta EE 9 can define new versions of the deployment descriptors and host them
on jakarta.ee.

**Comment by kwsutter** [comment]
@ivargrimstad is working with the Eclipse Foundation to find an appropriate location for these schemas.  Once that is decided, then we can use this Issue to update the schemas themselves which are housed in different repo:  https://github.com/eclipse-ee4j/jakartaee-schemas

**Comment by kwsutter** [comment]
Ivar's xml namespace work with Eclipse is being tracked via this [Issue #592](https://github.com/jakartaee/jakarta.ee/issues/592).

**Comment by kwsutter** [comment]
This issue should be resolved.  All of our schemas are now moved to the new namespace:
https://jakarta.ee/xml/ns/jakartaee/#9
