### ISSUE TITLE
Statement on deprecation of permissions.xml in specs

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#460]
With the future deprecation of the SecurityManager, should we deprecate in reference to permissions/permissions.xml configuration in EE 10, prune in EE 11?

Continue discussion on https://www.eclipse.org/lists/jakartaee-platform-dev/msg03175.html

**Comment by joakime** [comment]
"the future deprecation of SecurityManager" ?

It is deprecated, already.

See https://openjdk.java.net/jeps/411 - this was delivered in the JDK 17 release.

All of the following are currently deprecated as of JDK 17 (and JEP-411)

* java.lang.SecurityManager
* java.lang.System::{setSecurityManager, getSecurityManager}
* java.security.{Policy, PolicySpi, Policy.Parameters}
* java.security.{AccessController, AccessControlContext, AccessControlException, DomainCombiner} 
* java.lang.Thread::checkAccess
* java.lang.ThreadGroup::checkAccess
* java.util.logging.LogManager::checkAccess
* java.util.concurrent.Executors::{privilegedCallable, privilegedCallableUsingCurrentClassLoader, privilegedThreadFactory}
* java.rmi.RMISecurityManager
* javax.security.auth.SubjectDomainCombiner
* javax.security.auth.Subject::{doAsPrivileged, getSubject}

A future JEP will removal the SecurityManager and related methods and classes.

Work is already underway in JDK 18 ...

See also https://mail.openjdk.java.net/pipermail/jdk-dev/2021-May/005616.html

> We plan to change the default value of the 'java.security.manager' 
> system property to "disallow" in the next release, i.e., Java 18. That 
> will cause System::setSecurityManager to throw an 
> UnsupportedOperationException in Java 18.

**Comment by starksm64** [comment]
Correct. The baseline for EE10 is Java SE 11 and the SM is still fully functional in SE 17. At that time of opening this issue it was not clear if there would be a way to go forward with similar functionality based on new APIs in the JDK, but recent discussions point to this being not possible. We will create a statement saying the EE10 will be the last release with requirements around a security manager, and that TCK tests may have to be excluded in future point releases if vendors are certifying newer SE releases against EE10 and earlier.

**Comment by starksm64** [comment]
We have added a statement that the SecurityManager is deprecated for removal as of EE10.
