### ISSUE TITLE
Grant Triage user permissions to contributor...

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#463]
Could one of the Platform committers please grant `triage` permissions to `smarlow@redhat.com`.  The instructions for how to grant `triage` permissions [are listed here](https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-%E2%80%9CTriage%E2%80%9D-access#how-committers-grant-triage-access-to-contributors).

I'm looking forward to using the [Github `triage` permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role) to add a wiki page on the Platform Wiki describing the content listed in [this comment](https://github.com/eclipse-ee4j/jakartaee-platform/issues/339#issuecomment-1024302162) regarding split-off TCK handling (wiki page can then be reviewed and edited),

**Comment by starksm64** [comment]
Should be added.

**Comment by scottmarlow** [comment]
I don't seem to have edit permissions on the Platform Wiki yet.
