### ISSUE TITLE
Compatibility certification request for Open Liberty 22.0.0.3-beta for Jakarta Concurrency 3.0 (of Jakarta EE 10)

### ISSUE THREAD

**Issue by njr-11** [eclipse-ee4j/jakartaee-platform#464]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [IBM Corporation](https://www.ibm.com/)

- [ ] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty 22.0.0.3-beta](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/2022-02-01_1901/openliberty-22.0.0.3-beta.zip) (check link on Feb 15)

- [x] Specification Name, Version and download URL:<br/>
   [Jakarta Concurrency 3.0](https://jakarta.ee/specifications/concurrency/3.0)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  Jakarta Concurrency 3.0 TCK [staging](https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/enterprise/concurrent/jakarta.enterprise.concurrent-tck/3.0.0/jakarta.enterprise.concurrent-tck-3.0.0.jar) | [mirrored](https://public.dhe.ibm.com/ibmdl/export/pub/software/olrepo/io/openliberty/jakarta/enterprise/concurrent/jakarta.enterprise.concurrent-tck/3.0.0.20220126/jakarta.enterprise.concurrent-tck-3.0.0.20220126.jar) | [SHA](https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/enterprise/concurrent/jakarta.enterprise.concurrent-tck/3.0.0/jakarta.enterprise.concurrent-tck-3.0.0.pom.sha1) 5d26b855cb6148b23cb34e2e721f6cc8ca9d369e

- [ ] Public URL of TCK Results Summary:<br/>
  [Java 11 TCK results](https://openliberty.io/certifications/jakartaee/10/concurrency/22.0.0.3-beta-Java11-TCKResults.html) (check link on Feb 15)
  [Java 17 TCK results](https://openliberty.io/certifications/jakartaee/10/concurrency/22.0.0.3-beta-Java17-TCKResults.html) (check link on Feb 15)

- [x] Any Additional Specification Certification Requirements:<br/>
  [General Instructions to run the TCK](https://github.com/eclipse-ee4j/concurrency-api/tree/master/tck)
  [Instructions to run the TCK with Open Liberty](https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.concurrency.3.0_fat_tck)

- [x] Java runtime used to run the implementation:<br/>
  IBM Semeru Runtime Open Edition (11.0.13+8)
  IBM Semeru Runtime Open Edition (17.0.1+12)

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux RHEL 8

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
This CCR should be submitted to the Concurrency project [issue tracker](https://github.com/eclipse-ee4j/concurrency-api/issues).
I'm not sure if it is possible to move it, or if you have to create a new issue there and copy the content...

**Comment by njr-11** [comment]
> This CCR should be submitted to the Concurrency project [issue tracker](https://github.com/eclipse-ee4j/concurrency-api/issues).
I'm not sure if it is possible to move it, or if you have to create a new issue there and copy the content...

Thanks for pointing that out. I have copied it to here and am closing out this current issue (464)
https://github.com/eclipse-ee4j/concurrency-api/issues/175
