### ISSUE TITLE
Compatibility certification request for xigemaAS 9.1 for Full Platform

### ISSUE THREAD

**Issue by vsettanTCK** [eclipse-ee4j/jakartaee-platform#472]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Beijing Vsettan Data Technology Co. Ltd.](http://www.vsettan.com.cn/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  [xigemaAS 9.1](http://www.vsettan.com.cn/7752.html)
- [x] Specification Name, Version and download URL:<br/>
   [Jakarta EE Platform, Full Profile 8.0](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 8.0.2](https://download.eclipse.org/jakartaee/platform/8/eclipse-jakartaeetck-8.0.2.zip) SHA-256: 14a21b617bb646055c2952f1422ec04a71389fb37301e1c2969f6c3700aee965
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results](http://www.vsettan.com.cn/10073.html)
- [x] Any Additional Specification Certification Requirements:<br/>
  Jakarta Contexts and Dependency Injection
  [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip)  SHA-256: 75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808

  Jakarta Bean Validation
  [beanvalidation-tck-dist-2.0.5.tar.gz](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.tar.gz)  SHA-256: 05afb564efaa6d893dbeb32fb614d6e2bd18f09cf76244386f3b377d725b14b8
   
  Jakarta Injection
  [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip)  SHA-256: b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f
- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 8 (jdk8u222-b10)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Apache Derby 10.14.2.0, CentOS Linux release 7.9.2009 (Core)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
+1 LGTM

**Comment by vsettanTCK** [comment]
Thank a lot @ivargrimstad
