### ISSUE TITLE
Compatibility certification request for WildFly 27.0.0.Alpha1 (SE 11) for Core Profile

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#493]
- [x] Organization Name ("Organization") and, if applicable, URL+
  Red Hat, Inc., http://redhat.com
- [x] Product Name, Version and download URL (if applicable)+
WildFly 27.0.0.Alpha1, https://github.com/wildfly/wildfly/releases/download/27.0.0.Alpha1/wildfly-preview-27.0.0.Alpha1.zip
- [x] Specification Name, Version and download URL+
 Jakarta Core Profile 10.0
- [x] TCK Version, digital SHA-256 fingerprint and download URL+
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip, 702a84e3c6532fb0aad6a37443bf5e7fadbfb7cf0071271f3a1fdd10cab1229c
- [x] Public URL of TCK Results Summary+
https://github.com/jakartaredhat/wf-core-tck-runner/wiki/Jakarta-Core-Profile-10.0.0-TCK-Java-SE-11-Results
- [x] Java runtime used to run the implementation+
OpenJDK Runtime Environment Temurin-11.0.13+8 (build 11.0.13+8)
- [x] Summary of the information for the certification environment, operating system, cloud,+
Linux basic-k3x30 5.14.14-200.fc34.x86_64  SMP Wed Oct 20 16:15:12 UTC 2021 x86_64 GNU/Linux
- [x] By checking this box I acknowledge that I accept the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
Great to see! Everything looks fine to me. 
One question though: Doesn't it need to run with Java 11 in order to be used for ratification? We will also need a pass on Java 17.

**Comment by ivargrimstad** [comment]
The test log states 11.0.13, so I guess it is just a matter of updating the issue.

**Comment by starksm64** [comment]
Yes, it was run with SE 11, so I have updated that. I was going to do a separate CCR for the SE 17 run.

**Comment by smillidge** [comment]
The TCK link just links to the TCK for Dependency Injection. Is there no Core Profile TCK?

**Comment by starksm64** [comment]
Copy paste error. This core profile tck link has been corrected.

**Comment by Pandrex247** [comment]
The TCK link and SHA is incorrect.
The one currently published to staging is https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip and 476624b0967ca6976378071f965107963c401b24a71d0504f3945a48a52e754b

**Comment by Emily-Jiang** [comment]
@starksm64 did you rerun the tests against the latest released jax-rs tck?

**Comment by starksm64** [comment]
Yes, those results are using the lastest core profile tck bundle which has the 3.1.1 rest tck.

**Comment by Pandrex247** [comment]
The download URL for the TCK is wrong - it shouldn't have the `-dist`.
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip

**Comment by starksm64** [comment]
Ok, corrected TCK liink.
