### ISSUE TITLE
Deprecate Managed Beans in EE 10 for later removal

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-platform#502]
In a discussion around Managed Beans removal, it was clear there was pretty much unanimous support, and getting the deprecation into EE 10 for later removal was considered important.

**Comment by hantsy** [comment]
A basic Managed bean usage includes @ManagedBean, @PostConstruct @PreDestroy, what the replacement of them?

**Comment by starksm64** [comment]
Any of the CDI bean defining annotations replace `@ManagedBean`:
```
The set of bean defining annotations contains:

* `@ApplicationScoped` and `@RequestScoped` annotations,
* all other normal scope types,
* `@Interceptor` annotation,
* all stereotype annotations (i.e. annotations annotated with `@Stereotype`),
* and the `@Dependent` scope annotation.
```
`@PostConstruct`, `@PreDestroy` continue to be supported for CDI beans as they have been.
