### ISSUE TITLE
Compatibility certification request for  Eclipse GlassFish 7.0 M8 for Full Platform 10

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-platform#514]
- [X] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://eclipse.org) <br/><br/>
- [X] Product Name, Version and download URL (if applicable):
   [glassfish-7.0.0-M8.zip](https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-M8.zip) <br/><br/>
- [X] Specification Name, Version and download URL:
  [Jakarta EE Platform 10](https://jakarta.ee/specifications/platform/10) <br/><br/>
- [X] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta EE Platform TCK 10.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip)
  SHA-256: `7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e` <br/><br/> 
- [X] Public URL of TCK Results Summary:
  [Eclipse GlassFish 7.0 M8 TCK Results](https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0.0-M8) <br/><br/>
- [X] Any Additional Specification Certification Requirements:
  [Jakarta Concurrency 3.0.2 TCK](https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip),
  SHA-256: `22728d729f620d6a85ae903e7d1184e0a7508a4328491b785f1b4f3d7215ca93` <br/>
  [Jakarta JSON Processing 2.1.0 TCK](https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.0.zip), 
  SHA-256: `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`<br/>
  [Jakarta JSON Binding 3.0 TCK](https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip),
  SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b` <br/>
  [Jakarta RESTful Web Services 3.1.0 TCK](https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.0.zip), 
  SHA-256: `ea8cd6cc857af55f19468bbb09e8a30f41c60e8f7413a093e7007c3902a49070` <br/>
  [Jakarta Security 3.0.0 TCK](https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.0.zip), 
  SHA-256: `696776046dfeaed74266a5d1c4dac7fea5437b6f51743b7fe10962dde755ff8f`<br/>
  [Jakarta Authentication 3.0.1 TCK](https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip), 
  SHA-256: `8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54` <br/>
  [Jakarta Faces 4.0.1 TCK](https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.1.zip), 
  SHA-256: `117fdbf8aee14ee162cc913ae055621f7e067b0be4dd14c4591be76b90a0dde5`<br/>
  [Jakarta Contexts and Dependency Injection 4.0.5 TCK](https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.5-dist.zip), 
  SHA-256: `56ce1046738f79d9bc19271bfb3fb57c667dc7b84122cfeff287f554b34b1377` <br/>
  [Jakarta Batch 2.1.1 TCK](https://download.eclipse.org/jakartaee/batch/2.1/jakarta.batch.official.tck-2.1.1.zip), 
  SHA-256: `0dd8ca0f35cc696ea86d0dffaa1301cf2786806832ea1b2a491d528eaa57b3b7` <br/>
  [Jakarta Activation 2.1 TCK](https://download.eclipse.org/jakartaee/activation/2.1/jakarta-activation-tck-2.1.0.zip), 
  SHA-256: `6c4aad27e45761dd9f3e0f8506f37edea41f42401465db750689145718b27a0b` <br/>
  [Jakarta Mail 2.1.0 TCK](https://download.eclipse.org/jakartaee/mail/2.1/jakarta-mail-tck-2.1.0.zip), 
  SHA-256: `6f02a92e0a5ef60260e65f95938cc566da2f93a3d269c3b321da0d787a3448a5` <br/>
  [Jakarta XML Binding 4.0.0 TCK](https://download.eclipse.org/jakartaee/xml-binding/4.0/jakarta-xml-binding-tck-4.0.0.zip), 
  SHA-256: `33fa6a39e6ac6b767316efc2f71fed3577c3d364dd1f532d410915c30a0b5b67` <br/>
  [Jakarta Bean Validation 3.0.1 TCK](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.1.zip), 
  SHA-256: `9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3` <br/>
  [Jakarta Dependency Injection 2.0.2 TCK](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip), 
  SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972` <br/>
  [Jakarta Debugging Support for Other Languages 2.0 TCK](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip)
  SHA-256: `71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc` <br/><br/>
- [X] Java runtime used to run the implementation:<br/>
  - Java 1 runtime used to run the implementation: <br/>
   ```
   openjdk version "11.0.2" 2019-01-15
   OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
   ```
  - Java 2 runtime used to run the implementation: <br/>
   ```
   openjdk version "17.0.1" 2021-10-19
   OpenJDK Runtime Environment (build 17.0.1+12-39)
   OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
   ```
- [X] Summary of the information for the certification environment, operating system, cloud, ...:
  Apache Derby, <br/>
  Debian GNU/Linux 10 (buster)<br/><br/>
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by kazumura** [comment]
@arjantijms 

>   [Jakarta EE Platform TCK 10.0](https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.0.zip), 

For the Platform TCK,  please use the staged location.

**Comment by edbratt** [comment]
The SHA SUM for BV appears to be incorrect. Please update here, and also on the TCK Results page for GlassFish. I believe the correct sum is: `9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3`

**Comment by arjantijms** [comment]
@edbratt 
SHA for Jakarta Validation has been updated. Results page PR is here: https://github.com/eclipse-ee4j/glassfish/pull/24042

**Comment by arjantijms** [comment]
@edbratt @scottmarlow is there anything else that needs to be done that prevents the ballot to start?

**Comment by edbratt** [comment]
> @edbratt @scottmarlow is there anything else that needs to be done that prevents the ballot to start?

The revised TCK Summary looks good to me. Thank you!

**Comment by arjantijms** [comment]
@edbratt I also did the stretch goal of updating to Authentication TCK 3.0.1 with new SHA `8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54`. It wasn't absolutely needed, but sure is a lot better I think.

**Comment by scottmarlow** [comment]
We still aren't yet ready to start the ballot for Web Profile + Core Profile due to Concurrency challenge https://github.com/jakartaee/concurrency/issues/244.  

The Concurrency issue doesn't have a code change merged yet (https://github.com/jakartaee/concurrency/pull/250 is likely to be the change made).

Could we start all of the ballots together at the same time to ensure that the [Concurrency issue](https://github.com/jakartaee/concurrency/issues/244) is completely understood and on track to being solved.  

Starting the ballots at the same time, doesn't guarantee that they will all complete at the same time but at least they will be in sync initially with regard to Concurrency TCK changes.

**Comment by OndroMih** [comment]
I've raised https://github.com/eclipse-ee4j/glassfish/pull/24050 to fix the issues in the TCK summary page (version and SHA value)

**Comment by ivargrimstad** [comment]
> I've raised [eclipse-ee4j/glassfish#24050](https://github.com/eclipse-ee4j/glassfish/pull/24050) to fix the issues in the TCK summary page (version and SHA value)

As soon as it is merged and available on the page, I can tick that box in the checklist as well

**Comment by arjantijms** [comment]
Merging has been done, but it hasn't shown up yet on https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0

**Comment by ivargrimstad** [comment]
> Merging has been done, but it hasn't shown up yet on https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0

Are you sure? https://github.com/eclipse-ee4j/glassfish/pull/24050 looks to be open still...

**Comment by OndroMih** [comment]
It wasn't merged yet, due to a glitch in the Eclipse ECA validation tool. I re-validated my email and the validation passed. The PR is merged now.

**Comment by OndroMih** [comment]
The website is published now. @arjantijms , can you please update the description to link the TCK Results Summary to https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0.0-M7?

**Comment by arjantijms** [comment]
@OndroMih 
> can you please update the description to link the TCK Results Summary to https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0.0-M7?

It is done, thanks!

**Comment by scottmarlow** [comment]
https://www.eclipse.org/lists/jakartaee-tck-dev/msg01693.html mentions some staged TCKs that I think should be released by the Specification Committee and the released TCKs should be referenced (I don't expect the SHA-256 to change since the staged TCKs are already using  EFTL license).

**Comment by arjantijms** [comment]
> and the released TCKs should be referenced in the issue

Done (SHAs stayed the same indeed). Note that the results page hosted at the GF site, which is largely a copy of the CCR, has the correct links as well.

**Comment by scottmarlow** [comment]
Note that https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/122/ passed with the newly generated [Platform TCK](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip)  with Platform TCK User Guide changes.  New sha-256 is `cfe4db9cf5f2bf5cfff568377f7a799c3dc4624e882585a0c659d781764183dd`

**Comment by scottmarlow** [comment]
The Platform TCK was built again yesterday for updating the release notes to refer to EE 10 + the current year.  

The sha256sum of the updated https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl//jakarta-jakartaeetck-10.0.0.zip is `69c5b275c61384a4435fa67613d7ac0178d2f39f4a12d9e511f76f6cdb2d2de0`

**Comment by arjantijms** [comment]
@edbratt The issue has been updated referencing the new platform TCK, incorporating Concurrency 3.0.2, and the updated GlassFish M8 release.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by edbratt** [comment]
LGTM -- the test results are identical for both SE 11 and 17. The TCK pass results are verified identical on both SE 11 and 17.

**Comment by hs536** [comment]
@arjantijms 
I'm sorry I didn't notice before, isn't the test item of concurrency-tck 148items?
https://glassfish.org/certifications/jakarta-platform/10/TCK-Results-7.0.0-M8
```
TCK Result Summary:

=============================================== jakarta-concurrency Total tests run: 149, Passes: 149, Failures: 0, Skips: 0 ===============================================
```
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-concurrency-tck-glassfish-run/122/testReport/
```

===============================================
jakarta-concurrency
Total tests run: 148, Passes: 148, Failures: 0, Skips: 0
===============================================

[INFO] Tests run: 148, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 225.763 s - in TestSuite
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 148, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
```

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee/.
