### ISSUE TITLE
Update Security API version in Jakarta Platform API 10.0.0

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/jakartaee-platform#519]
Discussed in https://github.com/jakartaee/security/issues/254

Currently the jakarta-platform api 10.0.0 does not contain the Security 3.0 API, I have to add it explicitly to find the new `OpenIdAuthenticationMechanismDefinition` annotation.

**Comment by starksm64** [comment]
I see this in the current staged 10.0.0 platform api jar:

https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/platform/jakarta.jakartaee-api/10.0.0/

```
└> wget https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/platform/jakarta.jakartaee-api/10.0.0/jakarta.jakartaee-api-10.0.0.jar -O /tmp/jakarta-api.jar
--2022-07-26 09:15:37--  https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/platform/jakarta.jakartaee-api/10.0.0/jakarta.jakartaee-api-10.0.0.jar
Resolving jakarta.oss.sonatype.org (jakarta.oss.sonatype.org)... 18.215.69.40, 184.72.125.87
Connecting to jakarta.oss.sonatype.org (jakarta.oss.sonatype.org)|18.215.69.40|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2282491 (2.2M) [application/java-archive]
Saving to: ‘/tmp/jakarta-api.jar’

/tmp/jakarta-api.ja 100%[===================>]   2.18M  2.80MB/s    in 0.8s    

2022-07-26 09:15:38 (2.80 MB/s) - ‘/tmp/jakarta-api.jar’ saved [2282491/2282491]

✏️ [starksm@Scotts-iMacPro#10388]-(wf-core-tck-runner.wiki)-[git://master ✔]-
└> jar -tf /tmp/jakarta-api.jar| grep OpenId 
jakarta/security/enterprise/identitystore/openid/OpenIdClaims.class
jakarta/security/enterprise/identitystore/openid/OpenIdContext.class
jakarta/security/enterprise/authentication/mechanism/http/openid/OpenIdProviderMetadata.class
jakarta/security/enterprise/authentication/mechanism/http/openid/OpenIdConstant.class
jakarta/security/enterprise/authentication/mechanism/http/OpenIdAuthenticationMechanismDefinition.class
```

**Comment by hantsy** [comment]
![dep](https://user-images.githubusercontent.com/854520/181033187-31b0f6f9-1ba8-4435-9163-674da28e8cb5.png)

![jakartaee10-sec](https://user-images.githubusercontent.com/854520/181031567-2feaa916-98f8-47e5-b8af-9a87b023a595.png)

**Comment by hantsy** [comment]
OK, remove the existing jars in .m2, and refresh the my project to update the dependencies, it is updated. 

Thanks.

BTW, is there a bom for 10.0.0?

**Comment by starksm64** [comment]
There is a staged bom here:
https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/platform/jakarta.jakartaee-bom/10.0.0/

**Comment by hantsy** [comment]
@starksm64 Thanks.
