### ISSUE TITLE
Compatibility certification request for Payara Server Community 6.2022.1.Alpha3 for Core Profile

### ISSUE THREAD

**Issue by Pandrex247** [eclipse-ee4j/jakartaee-platform#533]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  - Payara Services Ltd.
- [x] Product Name, Version and download URL (if applicable):<br/>
  - [Payara Server Community 6.2022.1.Alpha3](https://www.payara.fish/downloads/payara-platform-community-edition/)
- [x] Specification Name, Version and download URL:<br/>
   - Name: Jakarta Core Profile
   - Version: 10.0
   - Download URL: https://jakarta.ee/specifications/coreprofile/10/
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  - Version: 10.0.0
  - SHA-256: `702a84e3c6532fb0aad6a37443bf5e7fadbfb7cf0071271f3a1fdd10cab1229c`
  - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip
- [x] Public URL of TCK Results Summary:<br/>
  - https://docs.payara.fish/community/docs/6.2022.1.alpha3/Jakarta%20EE%20Certification/6.2022.1.Alpha3/6.2022.1.Alpha3%20Core%20TCK%20Results.html
- [x] Any Additional Specification Certification Requirements:<br/>
  - Jakarta Concurrency 3.0.1-SNAPSHOT TCK
    - Download URL: [concurrency-tck-3.0.1-SNAPSHOT-dist.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/epl/concurrency-tck-3.0.1-SNAPSHOT-dist.zip)
    - SHA-256: `21b5dd8bbafba6bf2b897a426d2184b3b3998d545b7bdb2eb6681bdd4d33b4c1`
  - Jakarta Contexts and Dependency Injection 4.0.6 TCK
    - Download URL: [cdi-tck-4.0.6-dist.zip](https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.6-dist.zip)
    - SHA-256:  `5da8beecb66937d2272fec95fa37a01c5b9b459fcccd5f8f5f12193e6bfd9710`
  - Jakarta Dependency Injection 2.0.1 TCK
    - Download URL: [jakarta.inject-tck-2.0.1-bin.zip](https://download.eclipse.org/ee4j/cdi/inject/2.0/jakarta.inject-tck-2.0.1-bin.zip)
    - SHA-256: `7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6`
  - Jakarta RESTful Web Services 3.1.1 TCK
    - Download URL: [jakarta-restful-ws-tck-3.1.1.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip)
    - SHA-256: `2ff33625931c5df8631a016bd25daabed9b27c81d72b7d2bfe6cab21b121cf1b`
    - Challenges:
      - https://github.com/jakartaee/rest/issues/1123 in JAX-RS TCK
  - Jakarta JSON Binding 3.0.0 TCK
    - Download URL: [jakarta-jsonb-tck-3.0.0.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jsonb-tck-3.0.0.zip)
    - SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
  - Jakarta JSON Processing 2.1.0 TCK
    - Download URL: [jakarta-jsonp-tck-2.1.0.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jsonp-tck-2.1.0.zip)
    - SHA-256: `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54` 
- [x] Java runtime used to run the implementation:<br/>
  - OpenJDK Runtime Environment Zulu11.54+25-CA (build 11.0.14.1+1-LTS)
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  - Linux: Ubuntu 20.04 LTS
  - Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
I don't think you have filed an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) yet to get listed on https://jakarta.ee/.
