### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 7.0 M8 for Web Profile 10

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-platform#534]
- [X] Organization Name ("Organization") and, if applicable, URL:
  [Eclipse Foundation](https://eclipse.org) <br/><br/>
- [X] Product Name, Version and download URL (if applicable):
   Eclipse GlassFish Web Profile [web-7.0.0-M8.zip](https://download.eclipse.org/ee4j/glassfish/web-7.0.0-M8.zip) <br/><br/>
- [X] Specification Name, Version and download URL:
  [Jakarta EE Platform Web Profile 10](https://jakarta.ee/specifications/webprofile/10) <br/><br/>
- [X] TCK Version, digital SHA-256 fingerprint and download URL:
  [Jakarta EE Platform TCK 10.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip)
  SHA-256: `7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e` <br/><br/> 
- [X] Public URL of TCK Results Summary:
  [Eclipse GlassFish Web Profile 7.0 M8 TCK Results](https://glassfish.org/certifications/jakarta-web-profile/10/TCK-Results-7.0.0-M8) <br/><br/>
- [X] Any Additional Specification Certification Requirements:
  [Jakarta Concurrency 3.0.2 TCK](https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip),
  SHA-256: `22728d729f620d6a85ae903e7d1184e0a7508a4328491b785f1b4f3d7215ca93` <br/>
  [Jakarta JSON Processing 2.1.0 TCK](https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.0.zip), 
  SHA-256: `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`<br/>
  [Jakarta JSON Binding 3.0 TCK](https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip),
  SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b` <br/>
  [Jakarta RESTful Web Services 3.1.0 TCK](https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.0.zip), 
  SHA-256: `ea8cd6cc857af55f19468bbb09e8a30f41c60e8f7413a093e7007c3902a49070` <br/>
  [Jakarta Security 3.0.0 TCK](https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.0.zip), 
  SHA-256: `696776046dfeaed74266a5d1c4dac7fea5437b6f51743b7fe10962dde755ff8f`<br/>
  [Jakarta Authentication 3.0.1 TCK](https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip), 
  SHA-256: `8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54` <br/>
  [Jakarta Faces 4.0.1 TCK](https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.1.zip), 
  SHA-256: `117fdbf8aee14ee162cc913ae055621f7e067b0be4dd14c4591be76b90a0dde5`<br/>
  [Jakarta Contexts and Dependency Injection 4.0.5 TCK](https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.5-dist.zip), 
  SHA-256: `56ce1046738f79d9bc19271bfb3fb57c667dc7b84122cfeff287f554b34b1377` <br/>
  [Jakarta Batch 2.1.1 TCK](https://download.eclipse.org/jakartaee/batch/2.1/jakarta.batch.official.tck-2.1.1.zip), 
  SHA-256: `0dd8ca0f35cc696ea86d0dffaa1301cf2786806832ea1b2a491d528eaa57b3b7` <br/>
  [Jakarta Bean Validation 3.0.1 TCK](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.1.zip), 
  SHA-256: `9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3` <br/>
  [Jakarta Dependency Injection 2.0.2 TCK](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip), 
  SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972` <br/>
  [Jakarta Debugging Support for Other Languages 2.0 TCK](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip)
  SHA-256: `71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc` <br/><br/>
- [X] Java runtime used to run the implementation:<br/>
  - Java 1 runtime used to run the implementation: <br/>
   ```
   openjdk version "11.0.2" 2019-01-15
   OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
   ```
  - Java 2 runtime used to run the implementation: <br/>
   ```
   openjdk version "17.0.1" 2021-10-19
   OpenJDK Runtime Environment (build 17.0.1+12-39)
   OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
   ```
- [X] Summary of the information for the certification environment, operating system, cloud, ...:
  Apache Derby, <br/>
  Debian GNU/Linux 10 (buster)<br/><br/>
- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by Emily-Jiang** [comment]
@arjantijms can you confirm the test results are applicable to both Java versions (java 11 and 17) you noted in this issue?

**Comment by arjantijms** [comment]
@Emily-Jiang 
> can you confirm the test results are applicable to both Java versions (java 11 and 17) you noted in this issue?

Yes, I can confirm that.

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee.
