### ISSUE TITLE
Compatibility certification request for WildFly 27.0.0.Alpha5 for Full Platform 10

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-platform#539]
- [X] Organization Name ("Organization") and, if applicable, URL:<br/>
   [Red Hat](https://www.redhat.com)
- [X] Product Name, Version and download URL (if applicable):<br/>
   [WildFly 27.0.0.Alpha5](https://wildfly.org/downloads)
- [X] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform 10](https://jakarta.ee/specifications/platform/10)
- [X] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Platform TCK 10.0](https://download.eclipse.org/jakartaee/platform/10/jakarta-jakartaeetck-10.0.0.zip)
  SHA-256: `7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e`
- [X] Public URL of TCK Results Summary:<br/>
  [WildFly OpenJDK 17 TCK Results](https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-full-platform-jdk17.adoc)
  [WildFly OpenJDK 11 TCK Results](https://github.com/wildfly/certifications/blob/EE10/WildFly_27.0.0.Alpha5/jakarta-full-platform-jdk11.adoc)
- [X] Any Additional Specification Certification Requirements:<br/>
  [Jakarta Activation 2.1 TCK](https://download.eclipse.org/jakartaee/activation/2.1/jakarta-activation-tck-2.1.0.zip), 
  SHA-256: `6c4aad27e45761dd9f3e0f8506f37edea41f42401465db750689145718b27a0b`
  [Jakarta Authentication 3.0.1 TCK](https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip), 
  SHA-256: `8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54`
  [Jakarta Batch 2.1.1 TCK](https://download.eclipse.org/jakartaee/batch/2.1/jakarta.batch.official.tck-2.1.1.zip), 
  SHA-256: `0dd8ca0f35cc696ea86d0dffaa1301cf2786806832ea1b2a491d528eaa57b3b7`
  [Jakarta Bean Validation 3.0.1 TCK](https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.1.zip), 
  SHA-256: `9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3`
  [Jakarta Concurrency 3.0.2 TCK](https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip),
  SHA-256: `22728d729f620d6a85ae903e7d1184e0a7508a4328491b785f1b4f3d7215ca93`
  [Jakarta Contexts and Dependency Injection 4.0.5 TCK](https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.5-dist.zip), 
  SHA-256: `56ce1046738f79d9bc19271bfb3fb57c667dc7b84122cfeff287f554b34b1377`
  [Jakarta Debugging Support for Other Languages 2.0 TCK](https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip)
  SHA-256: `71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc`
  [Jakarta Dependency Injection 2.0.2 TCK](https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip),
  SHA-256: `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`
  [Jakarta Faces 4.0.1 TCK](https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.1.zip), 
  SHA-256: `117fdbf8aee14ee162cc913ae055621f7e067b0be4dd14c4591be76b90a0dde5`
  [Jakarta JSON Binding 3.0 TCK](https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip),
  SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
  [Jakarta JSON Processing 2.1.0 TCK](https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.0.zip), 
  SHA-256: `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`
  [Jakarta Mail 2.1.0 TCK](https://download.eclipse.org/jakartaee/mail/2.1/jakarta-mail-tck-2.1.0.zip), 
  SHA-256: `6f02a92e0a5ef60260e65f95938cc566da2f93a3d269c3b321da0d787a3448a5`
  [Jakarta RESTful Web Services 3.1.0 TCK](https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.0.zip), 
  SHA-256: `ea8cd6cc857af55f19468bbb09e8a30f41c60e8f7413a093e7007c3902a49070`
  [Jakarta Security 3.0.0 TCK](https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.0.zip), 
  SHA-256: `696776046dfeaed74266a5d1c4dac7fea5437b6f51743b7fe10962dde755ff8f`
  [Jakarta XML Binding 4.0.0 TCK](https://download.eclipse.org/jakartaee/xml-binding/4.0/jakarta-xml-binding-tck-4.0.0.zip), 
  SHA-256: `33fa6a39e6ac6b767316efc2f71fed3577c3d364dd1f532d410915c30a0b5b67`
- [X] Java runtime used to run the implementation:<br/>
  -  OpenJDK 17 runtime used to run the implementation:
   ```
   OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
   ```
  - OpenJDK 11 runtime used to run the implementation:
   ```
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7-LTS, mixed mode)
   ```
- [X] Summary of the information for the certification environment, operating system, cloud, ...:

  OS version: Red Hat Enterprise Linux Server 7.4 (Maipo)
  Database version:   Apache Derby Network Server 10.15.2.0
  Database JDBC Driver and version:  Apache Derby 10.15.2.0

- [X] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [X] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by bstansberry** [comment]
Note that this CCR assumes acceptance of the security TCK challenge at https://github.com/jakartaee/security/issues/270.

**Comment by bstansberry** [comment]
This is noted in the Jakarta 3.0 Security TCK sections of the two linked 'Public URL of TCK Results Summary' documents

```
Completed running 117 tests.
Number of Tests Failed      = 2 (two test failures are challenged via https://github.com/jakartaee/security/issues/270)
Number of Tests with Errors = 0
```

**Comment by bstansberry** [comment]
Following some discussion on the Sep 12 EE Platform Group call it sounded more proper for an impl to work around a challenged test (pending a TCK update) by excluding execution of the test, instead of reporting it failed, as we'd done in my comment above. So we updated our TCK runner for the Security TCK to do that, re-ran, and updated the linked 'Public URL of TCK Results Summary' documents. The Security TCK results sections now read as follows:


TCK result summary:
```
Completed running 115 tests.
Number of Tests Failed      = 0
Number of Tests with Errors = 0
```
```
[javatest.batch] Completed running 84 tests.
[javatest.batch] Number of Tests Passed      = 84
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
```
(Two tests were excluded due to the challenge at https://github.com/jakartaee/security/issues/270)

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee/.
