### ISSUE TITLE
Compatibility certification request for FJ-EAP 1.1.0 for Full Platform 10

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/jakartaee-platform#541]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [Fujitsu Limited](https://www.fujitsu.com/jp/)
  
- [x] Product Name, Version and download URL (if applicable):<br/>
  [FUJITSU Software Enterprise Application Platform 1.1.0](https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/)
  
- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform 10](https://jakarta.ee/specifications/platform/10)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip  
  SHA-256: 7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e

- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap110-ee10full-tck-results/#top)

- [x] Any Additional Specification Certification Requirements:<br/>
  * Jakarta Concurrency 3.0.2 TCK  
    Download URL: https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.2.zip  
    SHA-256: 22728d729f620d6a85ae903e7d1184e0a7508a4328491b785f1b4f3d7215ca93

  * Jakarta JSON Processing 2.1.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/jsonp/2.1/jakarta-jsonp-tck-2.1.0.zip  
    SHA-256: 6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54

  * Jakarta JSON Binding 3.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/jsonb/3.0/jakarta-jsonb-tck-3.0.0.zip  
    SHA-256: 954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b

  * Jakarta RESTful Web Services 3.1.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/restful-ws/3.1/jakarta-restful-ws-tck-3.1.0.zip  
    SHA-256: ea8cd6cc857af55f19468bbb09e8a30f41c60e8f7413a093e7007c3902a49070

  * Jakarta Security 3.0.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/security/3.0/jakarta-security-tck-3.0.0.zip  
    SHA-256: 696776046dfeaed74266a5d1c4dac7fea5437b6f51743b7fe10962dde755ff8f

  * Jakarta Authentication 3.0.1 TCK  
    Download URL: https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip  
    SHA-256: 8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54

  * Jakarta Faces 4.0.1 TCK  
    Download URL: https://download.eclipse.org/jakartaee/faces/4.0/jakarta-faces-tck-4.0.1.zip  
    SHA-256: 117fdbf8aee14ee162cc913ae055621f7e067b0be4dd14c4591be76b90a0dde5

  * Jakarta Contexts and Dependency Injection 4.0.5 TCK  
    Download URL: https://download.eclipse.org/jakartaee/cdi/4.0/cdi-tck-4.0.5-dist.zip  
    SHA-256: 56ce1046738f79d9bc19271bfb3fb57c667dc7b84122cfeff287f554b34b1377

  * Jakarta Batch 2.1.1 TCK  
    Download URL: https://download.eclipse.org/jakartaee/batch/2.1/jakarta.batch.official.tck-2.1.1.zip  
    SHA-256: 0dd8ca0f35cc696ea86d0dffaa1301cf2786806832ea1b2a491d528eaa57b3b7

  * Jakarta Activation 2.1 TCK  
    Download URL: https://download.eclipse.org/jakartaee/activation/2.1/jakarta-activation-tck-2.1.0.zip  
    SHA-256: 6c4aad27e45761dd9f3e0f8506f37edea41f42401465db750689145718b27a0b

  * Jakarta Mail 2.1.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/mail/2.1/jakarta-mail-tck-2.1.0.zip  
    SHA-256: 6f02a92e0a5ef60260e65f95938cc566da2f93a3d269c3b321da0d787a3448a5

  * Jakarta XML Binding 4.0.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/xml-binding/4.0/jakarta-xml-binding-tck-4.0.0.zip  
    SHA-256: 33fa6a39e6ac6b767316efc2f71fed3577c3d364dd1f532d410915c30a0b5b67

  * Jakarta Bean Validation 3.0.1 TCK  
    Download URL: https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.1.zip  
    SHA-256: 9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3

  * Jakarta Dependency Injection 2.0.2 TCK  
    Download URL: https://download.eclipse.org/jakartaee/dependency-injection/2.0/jakarta.inject-tck-2.0.2-bin.zip  
    SHA-256: 23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972

  * Jakarta Debugging Support for Other Languages 2.0 TCK  
    Download URL: https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip  
    SHA-256: 71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc
- [x] Java runtime used to run the implementation:<br/>
  OpenJDK 11.0.2
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  CentOS Linux 7.3, Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee/.

**Comment by hs536** [comment]
Please be informed that the URL for the TCK results page, which is referenced in this CCR, has been updated due to a change in our company's website policy.

Public URL of TCK Results Summary:
- before: https://www.fujitsu.com/jp/products/software/middleware/business-middleware/middleware/applatform/jakartaee-report/eap110-ee10full-tck-results/index.html
- after: https://docs.fujitsu/documents/002474/eap110-ee10full-tck-results.pdf
