### ISSUE TITLE
Compatibility certification request for Open Liberty for Jakarta EE 10, Core Profile, Java 11

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-platform#544]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  [IBM Corporation](https://www.ibm.com)

- [x] Product Name, Version and download URL (if applicable):<br/>
  [Open Liberty, 22.0.0.10-beta](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/22.0.0.10-beta/openliberty-22.0.0.10-beta.zip)

- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, Core Profile, 10.0](https://jakarta.ee/specifications/coreprofile/10)

- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  [Jakarta EE Core Profile TCK 10.0 (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-core-profile-tck-10.0.0.zip)
 `702a84e3c6532fb0aad6a37443bf5e7fadbfb7cf0071271f3a1fdd10cab1229c`

- [x] Public URL of TCK Results Summary:<br/>
  [Test Results](https://openliberty.io/certifications/jakartaee/10/coreprofile/22.0.0.10-beta-Java11-TCKResults.html)

- [x] Any Additional Specification Certification Requirements:<br/>
  Jakarta Annotations
  [jakarta-annotations-tck-2.1.1.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-annotations-tck-2.1.1.zip)
 `8c2131d51c75cde4be74382f662519f9fd439f4ce4dd60832ed55b796e5f72f3`

  Jakarta Contexts and Dependency Injection
  [cdi-tck-4.0.7-dist.zip](https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.7-dist.zip)
 `683e09ed991b61992a491857345cce635dd9e61a1f17663e2fb993c9d0f6b781`

  Jakarta Dependency Injection
  [jakarta.inject-tck-2.0.2-bin.zip](https://download.eclipse.org/ee4j/cdi/inject/2.0/jakarta.inject-tck-2.0.2-bin.zip)
 `23bce4317ca061c3de648566cdf65c74b57e1264d6891f366567955d6b834972`

  Jakarta JSON Binding
  [jakarta-jsonb-tck-3.0.0.zip](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonb-tck-3.0.0.zip)
 `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`

  Jakarta JSON Processing
  [jakarta-jsonp-tck-2.1.0.zip](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/promoted/eftl/jakarta-jsonp-tck-2.1.0.zip)
 `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`

  Jakarta RESTful Web Services
  [jakarta-restful-ws-tck-3.1.1.zip (Staged Release)](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip)
 `2ff33625931c5df8631a016bd25daabed9b27c81d72b7d2bfe6cab21b121cf1b`

- [x] Java runtime used to run the implementation:<br/>
  openjdk version "11.0.15" 2022-04-19
  IBM Semeru Runtime Certified Edition 11.0.15.0 (build 11.0.15+10)
  Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Linux amd64-64-Bit Compressed References 20220422_425 (JIT enabled, AOT enabled)
  OpenJ9   - 9a84ec34e
  OMR      - ab24b6666
  JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Ubuntu 18.04 LTS, Apache Derby

- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).

- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

- [x] Relevant challenges & resolution:
  RESTful Web Services TCK:
  [2 failures](https://github.com/jakartaee/rest/issues/1126)
  [7 tests excluded](https://github.com/jakartaee/rest/issues/1128)

**Comment by ivargrimstad** [comment]
LGTM

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee/.
