### ISSUE TITLE
Compatibility certification request for Payara Server Community 6.2022.1.Alpha4 for Full Platform

### ISSUE THREAD

**Issue by Pandrex247** [eclipse-ee4j/jakartaee-platform#547]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  - [Payara Services Ltd.](https://www.payara.fish/)
- [x] Product Name, Version and download URL (if applicable):<br/>
  - Product Name: Payara Server Community
  - Version: 6.2022.1.Alpha4
  - Download URL: 
    - https://www.payara.fish/downloads/payara-platform-community-edition/
    - https://github.com/payara/Payara/releases/tag/payara-server-6.2022.1.Alpha4
- [x] Specification Name, Version and download URL:<br/>
   - Specification Name: Jakarta EE Platform
   - Version: 10.0
   - Download URL: https://jakarta.ee/specifications/platform/10
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
  - TCK Version: 10.0.0 (Staged)
  - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jakartaeetck-10.0.0.zip
  - SHA-256: 7874244f69ed9c72f4d4b5a8c48b21d39c56f4b877b1d4d735247a7f08215a5e
- [x] Public URL of TCK Results Summary:<br/>
  - [Payara Documentation](https://docs.payara.fish/community/docs/6.2022.1.alpha4/Jakarta%20EE%20Certification/6.2022.1.Alpha4/6.2022.1.Alpha4%20Platform%20TCK%20Results.html)
- [x] Any Additional Specification Certification Requirements:<br/>
  - Jakarta Activation 2.1.0 TCK
    - Download URL: https://download.eclipse.org/jakartaee/activation/2.1/jakarta-activation-tck-2.1.0.zip
      - SHA-256: `6c4aad27e45761dd9f3e0f8506f37edea41f42401465db750689145718b27a0b`
  - Jakarta Authentication 3.0.1 TCK
    - Download URL: https://download.eclipse.org/jakartaee/authentication/3.0/jakarta-authentication-tck-3.0.1.zip
      - SHA-256: `8b916f1b4aed828337bd88b34bb39b133f04611c2dfe71541c2ec5d2dd22cd54`
  - Jakarta Batch 2.1.1 TCK
    - Download URL: https://download.eclipse.org/jakartaee/batch/2.1/jakarta.batch.official.tck-2.1.1.zip
      - SHA-256:  `0dd8ca0f35cc696ea86d0dffaa1301cf2786806832ea1b2a491d528eaa57b3b7`
  - Jakarta Bean Validation 3.0.1 TCK
    - Download URL: https://download.eclipse.org/jakartaee/bean-validation/3.0/beanvalidation-tck-dist-3.0.1.zip
      - SHA-256: `9da36d2d6e2eb8d413f886f15711820008419d210ce4c51af04f96e1ffd583b3`
  - Jakarta Concurrency 3.0.1 TCK
    - Download URL: https://download.eclipse.org/jakartaee/concurrency/3.0/concurrency-tck-3.0.1.zip
      - SHA-256: `ae6c9ec725f10f66ee196e604af77abf970b20556fe1bb78ed01638865f4e228`
  - Jakarta Contexts and Dependency Injection 4.0.6 TCK
    - Download URL: https://download.eclipse.org/ee4j/cdi/4.0/cdi-tck-4.0.6-dist.zip
      - SHA-256: `5da8beecb66937d2272fec95fa37a01c5b9b459fcccd5f8f5f12193e6bfd9710`
  - Jakarta Debugging Support for Other Languages 2.0.0 TCK
    - Download URL: https://download.eclipse.org/jakartaee/debugging/2.0/jakarta-debugging-tck-2.0.0.zip
      - SHA-256: `71999815418799837dc6f3d0dc40c3dcc4144cd90c7cdfd06aa69270483d78bc`
  - Jakarta Dependency Injection 2.0.1 TCK
    - Download URL: https://download.eclipse.org/ee4j/cdi/inject/2.0/jakarta.inject-tck-2.0.1-bin.zip
      - SHA-256: `7853d02d372838f8300f5a18cfcc23011c9eb9016cf3980bba9442e4b1f8bfc6`
  - Jakarta JSON Binding 3.0.0 TCK (Staged Release)
    - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jsonb-tck-3.0.0.zip
      - SHA-256: `954fd9a3a67059ddeabe5f51462a6a3b542c94fc798094dd8c312a6a28ef2d0b`
  - Jakarta JSON Processing 2.1.0 TCK (Staged Release)
    - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-jsonp-tck-2.1.0.zip
      - SHA-256: `6ee953382ff965627fe20dd7e3bfce6c968ed829d611cf4990988ab54bfe8b54`
  - Jakarta Faces 4.0.1 TCK (Staged Release)
    - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-faces-tck-4.0.1.zip
      - SHA-256: `117fdbf8aee14ee162cc913ae055621f7e067b0be4dd14c4591be76b90a0dde5`
  - Jakarta Mail 2.1.0 TCK
    - Download URL: https://download.eclipse.org/jakartaee/mail/2.1/jakarta-mail-tck-2.1.0.zip
      - SHA-256: `6f02a92e0a5ef60260e65f95938cc566da2f93a3d269c3b321da0d787a3448a5`
  - Jakarta RESTful Web Services 3.1.1 TCK (Staged Release)
    - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-restful-ws-tck-3.1.1.zip
      - SHA-256: `2ff33625931c5df8631a016bd25daabed9b27c81d72b7d2bfe6cab21b121cf1b`
    - Challenges raised against `ee.jakarta.tck.ws.rs.jaxrs21.ee.client.executor.rx.JAXRSClientIT` and `ee.jakarta.tck.ws.rs.jaxrs21.ee.client.rxinvoker.JAXRSClientIT`: https://github.com/jakartaee/rest/issues/1123
  - Jakarta Security 3.0.0 TCK (Staged Release)
    - Download URL: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-security-tck-3.0.0.zip
      - SHA-256: `696776046dfeaed74266a5d1c4dac7fea5437b6f51743b7fe10962dde755ff8f`  
- [x] Java runtime used to run the implementation:<br/>
  - `OpenJDK Runtime Environment Zulu11.54+25-CA (build 11.0.14.1+1-LTS)`
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  - Apache Derby
  - Linux Ubuntu 20.04 LTS
  - Interoperatibility tests carried out against Eclipse Glassfish 7.0 (Nightly)
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
A couple of remarks:
- Some of the staged TCKs (at least authentication and activation) differ in sha256 from the released
- The listed concurrency TCK is a SNAPSHOT release
- I can't figure out what the JARs listed for Batch TCK are

**Comment by Pandrex247** [comment]
> Some of the staged TCKs (at least authentication and activation) differ in sha256 from the released

I checked those SHAs against those listed in the staged repo, which is what we were testing against.
If the released version has a different SHA that implies the staged release is different to that which is released correct? Are we not allowed to continue using the staged releases in this case?

> The listed concurrency TCK is a SNAPSHOT release

That's the only TCK that was staged - I'll look to update our runner to use one of the "final" downloads if we're not allowed to use that staged one.

> I can't figure out what the JARs listed for Batch TCK are

They're the staged maven artefacts from the staging repo itself: https://jakarta.oss.sonatype.org/content/groups/staging/jakarta/batch/
Specifically the ones aligning to the dependencies that contain the actual tests.
* https://github.com/eclipse-ee4j/batch-tck/tree/master/com.ibm.jbatch.tck
* https://github.com/eclipse-ee4j/batch-tck/tree/master/com.ibm.jbatch.tck.appbean
* https://github.com/eclipse-ee4j/batch-tck/tree/master/com.ibm.jbatch.tck.spi

Our TCK runner currently pulls those dependencies directly from the repo rather than doing any unpack & install with a zip - is that not allowed?

**Comment by Pandrex247** [comment]
I've just updated the issue with hopefully the correct SHAs and download URLs for Activation, Authentication, Batch, and Concurrency (re-ran the TCKs too to be sure).

The results in our documentation is currently rebuilding, but there are no changes in the actual results - just in the TCK downloads and SHAs.

**Comment by ivargrimstad** [comment]
Thanks!
It looks good now. I'll add the accepted label.

**Comment by ivargrimstad** [comment]
Congratulations!
Please proceed by filing an [issue](https://github.com/jakartaee/jakarta.ee/issues/new?template=compatibility.md) to get listed on https://jakarta.ee/.
