### ISSUE TITLE
Jakarta XML Web Services is not part of Java SE (Overview.adoc)

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jakartaee-platform#60]
File `overview.adoc` contains an innaccurate sentence "Jakarta XML Web Services, which is included in Java SE". This needs to be rephrased.

See https://github.com/eclipse-ee4j/jakartaee-platform/pull/53/files#r301357026 for context.

**Comment by bshannon** [comment]
JAX-WS is still in Java SE 8.

JAX-WS was contributed to Eclipse as Jakarta XML Web Services,
which can be considered for inclusion in a later version of Jakarta EE
that is based on Java SE 11, where JAX-WS no longer exists.

**Comment by keilw** [comment]
Related to #4

**Comment by bshannon** [comment]
This has been fixed in the latest version of the document.
