### ISSUE TITLE
Update new project name for Web Services Metadata specification

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jakartaee-platform#61]
`overview.adoc` references "Web Services Metadata specification", but we don't currently know the project this will be filled in. It was replaced to "Jakarta Enterprise Web Services" but will need to be revisited.

See https://github.com/eclipse-ee4j/jakartaee-platform/pull/53#discussion_r300826692 for context.

**Comment by bshannon** [comment]
"Web Services Metadata" and "Enterprise Web Services" are two different specs.
