### ISSUE TITLE
Inclusion of Jakarta Data in Jakarta EE 11

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jakartaee-platform#640]
Use this issue to discuss whether Jakarta Data should be included in Jakarta EE 11 and where should it be?

Web Profile is a candidate

[AB#29](https://dev.azure.com/jakarta-ee-azdo/7cf9a9d3-9854-41e0-9a66-99506a9ed874/_workitems/edit/29)

**Comment by hantsy** [comment]
I have used Microaunt Data and Spring Data in projects, compared to these
existing Repository solution, I think Jakarta Data needs more time to enter
the Jakarta main release train.
Currently in Jakarta EE 10, we lack reactivestreams(or Java 9 Flow) and
context propagate support in the core specs, such as http, cdi, tx, etc.
Jakarta EE 11 discussion leaves some room for the common spec, we could
consider these. Personally I like the idea,  and I would like to use all
akarta EE specs seamlessly like using Spring in the application
development,  not spend time researching the gap between specs.

I am not sure if the Jakarta Data 1.0 will include async, and reactive
streams( or Java 9 Flow API) support and if they(eg. Java 9 Flow) are
supported in other spec(servlet, faces, rest).
---

Regards,

*Hantsy Bai*

Self-employed consultant, fullstack developer, agile coach,
freelancer/remote worker

GitHub: https://github.com/hantsy

Twitter: ***@***.***
Medium: ***@***.***

**Comment by starksm64** [comment]
Red Hat will vote no on its inclusion. It needs more bake time in implementations.

**Comment by keilw** [comment]
@starksm64 Hopefully Red Hat also finds the time to participate as other provider reps do, especially given its mother company IBM co-chairs the spec? ;-)

Whenever it's considered ready (hopefully by Jakarta EE 12) I would not outrule the Core Platform either, but at least Web sounds fine.

**Comment by njr-11** [comment]
For all of those who have already decided on a No vote this early on, I'd like to collect your feedback about what is lacking from the 1.0 release of Jakarta Data.  (Thank you @hantsy for pointing out that you want to see Reactive/Flow included).  We still have 6 months of spec development timeframe at this point, and if you have concerns or specific requirements, it might be possible to add what you believe is lacking to version 1.0.  Over-generalized statements that the specification lacks maturity are not particularly helpful and are somewhat confusing given that the established products (Spring Data and Micronaut) are expected to become implementations of Jakarta Data.  It would be much more helpful to know exactly what from Spring Data and Micronaut that the Jakarta Data spec hasn't already standardized that you would like to see included.
