### ISSUE TITLE
Obtain better or create new images for Platform Spec document

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#74]
The images in our images directory are of very poor quality.  The conversion process that was used to get them to a usable format just didn't the images justice.  They are okay for Jakarta EE 8.  But, we should attempt to get better images from the Oracle team that did the initial conversion, or re-create them ourselves.

If you want an easy example to compare, look at the Jakarta EE Architecture Diagram in section 2.1 Architecture.  The text in this diagram is barely readable.  Especially if you compare it to the diagram in the original Java EE Platform Spec.

**Comment by bshannon** [comment]
Yes, and that's also an example of an image that will need to be recreated
so that we have an editable version.

**Comment by kwsutter** [comment]
Looks like this was partially resolved with PR #91.  There are about 11 more images we need to determine if they are worthwhile to improve.  Thus, I'll leave this Issue open for now.  The images provided by PR #91 are a huge improvement though.

**Comment by kwsutter** [comment]
I'm going to close this Issue.  @bshannon has provided all of the images that they had available at Oracle.  Thanks again!  So, if we determine that other images need to be updated or replaced, then we'll address them individually.
