### ISSUE TITLE
Code Blocks need cleanup in Platform spec

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#76]
The code blocks are not formatted correctly in the Platform spec. Hopefully, this will be an easy fixup.  I'm just documenting all of the items I am finding in case someone else can pick up these changes.

**Comment by NottyCode** [comment]
I volunteer

**Comment by keilw** [comment]
Shouldn't there be `.gitattributes` and `.editorconfig` files for that?

**Comment by kwsutter** [comment]
@keilw This is for the code samples that are embedded in the Platform Specification.  Look at the referenced PR #88.  It's not "real code", just blocks of sample code in the doc,.

**Comment by kwsutter** [comment]
This was resolved via PR #88.
