### ISSUE TITLE
Creation of javaee-api.jar and javaee-web-api.jar files

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jakartaee-platform#80]
Need to figure out how to create the javaee-api and javaee-web-api jar files based on the updated content in preparation for the Jakarta EE 8 release.

**Comment by romain-grecourt** [comment]
Bill did setup a new project based on what was used before: https://github.com/eclipse-ee4j/jakartaee-api

**Comment by bshannon** [comment]
Right, this is done.
