### ISSUE TITLE
LICENSE file should indicate EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

### ISSUE THREAD

**Issue by waynebeaton** [eclipse-ee4j/jakartaee-platform#90]
The LICENSE file in the root indicates EPL-2.0 only. It should be EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

A NOTICE file should also be included in the root. AFAICT, the NOTICE.md file in the "specification" directory is accurate.

**Comment by bshannon** [comment]
We were told to contribute the specification documents under EPL-2.0 only.
Since it's not code, the others don't seem relevant.

I'll move the NOTICE file.
