### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish 5.1 for Full Platform

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/jakartaee-platform#99]
- [x] Organization Name ("Organization") and, if applicable, URL:<br/>
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable):<br/>
  [Eclipse GlassFish 5.1](https://eclipse-ee4j.github.io/glassfish/download)
- [x] Specification Name, Version and download URL:<br/>
  [Jakarta EE Platform, 8](https://jakarta.ee/specifications/platform/8/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL:<br/>
   [Jakarta EE Platform TCK 8.0](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/eclipse-jakartaeetck-8.0.0.zip), SHA-256: `847c80c9c80bea4682006f186292b68acdd0ce9b239d998856c3a379c3a7be50`
- [x] Public URL of TCK Results Summary:<br/>
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-full-profile/8.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements:<br/>
  Jakarta Injection Specification
  [jakarta.inject-tck-1.0-bin.zip](https://download.eclipse.org/jakartaee/dependency-injection/1.0/jakarta.inject-tck-1.0-bin.zip),
  `b679bac9b1057df894753892a880ba6ade530607dd811157106ed767aa26481f`<br/>
  Jakarta Contexts and Dependency Injection
  [cdi-tck-2.0.6-dist.zip](https://download.eclipse.org/jakartaee/cdi/2.0/cdi-tck-2.0.6-dist.zip),
  `75e969a7a3b3c77332154a2008309aad821a923d8684139242048a7640762808`<br/>
  Jakarta Bean Validation
  [beanvalidation-tck-dist-2.0.5.zip](https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip),
  `4b10c1e850c871c0e47fd3c80177a81d855612085d4d2036aef4ea82b8db63d3`
- [x] Java runtime used to run the implementation:<br/>
  Oracle JDK 1.8.0_191
- [x] Summary of the information for the certification environment, operating system, cloud, ...:<br/>
  Linux Centos 7, Apache Derby
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by edbratt** [comment]
+1 looks good to me

**Comment by ivargrimstad** [comment]
+1

**Comment by scottmarlow** [comment]
I tried downloading the referenced https://download.eclipse.org/jakartaee/bean-validation/2.0/beanvalidation-tck-dist-2.0.5.zip and get a 404, are we in the middle of a rebuild perhaps?

**Comment by bshannon** [comment]
You can see from the [post-ballot checklist in the spec PR](https://github.com/jakartaee/specifications/pull/78#issuecomment-528041626) that the TCK hasn't been published yet.
I believe @dblevins  is still working on this so hopefully this will be done soon.

**Comment by bshannon** [comment]
+1

**Comment by bshannon** [comment]
Lacking any objections, I'm marking this approved by lazy consensus.

**Comment by carlosdlr** [comment]
+1
